/**
 * Mock Suggested Users Data
 * 10 users to follow
 */

import { SuggestedUser, PulseUser } from '@/types/pulse'

const suggestedUserProfiles: PulseUser[] = [
  {
    id: 'suggested-1',
    username: 'arjun_movies',
    display_name: 'Arjun Kapoor',
    avatar_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=ArjunSuggested',
    is_verified: true,
    bio: 'Film critic & movie enthusiast 🎬',
    follower_count: 45000,
    following_count: 523,
    pulse_count: 2341,
    created_at: '2023-03-20T14:30:00Z',
  },
  {
    id: 'suggested-2',
    username: 'priya_cricket',
    display_name: 'Priya Sharma',
    avatar_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=PriyaSuggested',
    is_verified: true,
    bio: 'Cricket analyst | Sports journalist 🏏',
    follower_count: 67000,
    following_count: 234,
    pulse_count: 3456,
    created_at: '2023-02-10T09:15:00Z',
  },
  {
    id: 'suggested-3',
    username: 'neha_reviews',
    display_name: 'Neha Gupta',
    avatar_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=NehaSuggested',
    is_verified: true,
    bio: 'Movie reviewer | YouTuber 📹',
    follower_count: 89000,
    following_count: 456,
    pulse_count: 1890,
    created_at: '2023-04-12T11:20:00Z',
  },
  {
    id: 'suggested-4',
    username: 'ananya_films',
    display_name: 'Ananya Reddy',
    avatar_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=AnanyaSuggested',
    is_verified: true,
    bio: 'Film student | Aspiring director 🎥',
    follower_count: 23000,
    following_count: 678,
    pulse_count: 890,
    created_at: '2023-07-22T15:30:00Z',
  },
  {
    id: 'suggested-5',
    username: 'rohit_sports',
    display_name: 'Rohit Verma',
    avatar_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=RohitSuggested',
    is_verified: false,
    bio: 'Sports commentator | Cricket lover',
    follower_count: 34000,
    following_count: 890,
    pulse_count: 1234,
    created_at: '2023-05-18T10:00:00Z',
  },
  {
    id: 'suggested-6',
    username: 'kavya_cinema',
    display_name: 'Kavya Iyer',
    avatar_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=KavyaSuggested',
    is_verified: true,
    bio: 'Bollywood insider | Entertainment news',
    follower_count: 56000,
    following_count: 345,
    pulse_count: 2567,
    created_at: '2023-06-05T12:45:00Z',
  },
  {
    id: 'suggested-7',
    username: 'aditya_classics',
    display_name: 'Aditya Menon',
    avatar_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=AdityaSuggested',
    is_verified: false,
    bio: 'Classic cinema enthusiast | Film historian',
    follower_count: 18000,
    following_count: 1200,
    pulse_count: 678,
    created_at: '2023-08-14T16:20:00Z',
  },
  {
    id: 'suggested-8',
    username: 'sneha_ipl',
    display_name: 'Sneha Patel',
    avatar_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=SnehaSuggested',
    is_verified: true,
    bio: 'IPL analyst | Cricket stats geek 📊',
    follower_count: 42000,
    following_count: 567,
    pulse_count: 1890,
    created_at: '2023-03-28T14:10:00Z',
  },
  {
    id: 'suggested-9',
    username: 'karthik_hollywood',
    display_name: 'Karthik Nair',
    avatar_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=KarthikSuggested',
    is_verified: false,
    bio: 'Hollywood buff | Oscar predictions expert',
    follower_count: 29000,
    following_count: 789,
    pulse_count: 1123,
    created_at: '2023-07-09T11:30:00Z',
  },
  {
    id: 'suggested-10',
    username: 'divya_director',
    display_name: 'Divya Krishnan',
    avatar_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=DivyaSuggested',
    is_verified: true,
    bio: 'Independent filmmaker | Storyteller 🎬',
    follower_count: 31000,
    following_count: 423,
    pulse_count: 945,
    created_at: '2023-04-25T09:50:00Z',
  },
]

export const mockSuggestedUsers: SuggestedUser[] = [
  {
    user: suggestedUserProfiles[0],
    reason: 'Popular in Movies',
    mutual_followers_count: 12,
  },
  {
    user: suggestedUserProfiles[1],
    reason: 'Popular in Cricket',
    mutual_followers_count: 8,
  },
  {
    user: suggestedUserProfiles[2],
    reason: 'Followed by 5 people you follow',
    mutual_followers_count: 5,
  },
  {
    user: suggestedUserProfiles[3],
    reason: 'Similar interests',
    mutual_followers_count: 3,
  },
  {
    user: suggestedUserProfiles[4],
    reason: 'Popular in Sports',
    mutual_followers_count: 7,
  },
  {
    user: suggestedUserProfiles[5],
    reason: 'Trending in Bollywood',
    mutual_followers_count: 9,
  },
  {
    user: suggestedUserProfiles[6],
    reason: 'Classic cinema expert',
    mutual_followers_count: 4,
  },
  {
    user: suggestedUserProfiles[7],
    reason: 'IPL specialist',
    mutual_followers_count: 6,
  },
  {
    user: suggestedUserProfiles[8],
    reason: 'Hollywood insider',
    mutual_followers_count: 2,
  },
  {
    user: suggestedUserProfiles[9],
    reason: 'Independent filmmaker',
    mutual_followers_count: 11,
  },
]

