"""add box office domain

Revision ID: 4f6f1d334794
Revises: aa9093843641
Create Date: 2025-10-18 14:10:57.337170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f6f1d334794'
down_revision: Union[str, Sequence[str], None] = 'aa9093843641'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('box_office_perf_genre',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('region', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('percent', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_box_office_perf_genre_region'), 'box_office_perf_genre', ['region'], unique=False)
    op.create_table('box_office_perf_monthly',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('region', sa.String(length=50), nullable=False),
    sa.Column('month', sa.String(length=10), nullable=False),
    sa.Column('gross_millions_usd', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_box_office_perf_monthly_region'), 'box_office_perf_monthly', ['region'], unique=False)
    op.create_table('box_office_perf_studio',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('region', sa.String(length=50), nullable=False),
    sa.Column('studio', sa.String(length=100), nullable=False),
    sa.Column('gross_millions_usd', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_box_office_perf_studio_region'), 'box_office_perf_studio', ['region'], unique=False)
    op.create_table('box_office_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('region', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('value_text', sa.String(length=50), nullable=False),
    sa.Column('year', sa.String(length=10), nullable=False),
    sa.Column('poster_url', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_box_office_records_region'), 'box_office_records', ['region'], unique=False)
    op.create_table('box_office_trends',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('region', sa.String(length=50), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('gross_millions_usd', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_box_office_trends_region'), 'box_office_trends', ['region'], unique=False)
    op.create_table('box_office_ytd',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('region', sa.String(length=50), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('total_gross_usd', sa.Float(), nullable=False),
    sa.Column('change_percent', sa.Float(), nullable=False),
    sa.Column('is_positive', sa.Boolean(), nullable=False),
    sa.Column('previous_year', sa.Integer(), nullable=False),
    sa.Column('previous_total_gross_usd', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_box_office_ytd_region'), 'box_office_ytd', ['region'], unique=False)
    op.create_index(op.f('ix_box_office_ytd_year'), 'box_office_ytd', ['year'], unique=False)
    op.create_table('box_office_weekend_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('region', sa.String(length=50), nullable=False),
    sa.Column('period_start', sa.DateTime(), nullable=True),
    sa.Column('period_end', sa.DateTime(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=True),
    sa.Column('weekend_gross_usd', sa.Float(), nullable=False),
    sa.Column('total_gross_usd', sa.Float(), nullable=False),
    sa.Column('change_percent', sa.Float(), nullable=True),
    sa.Column('is_positive', sa.Boolean(), nullable=False),
    sa.Column('weeks_in_release', sa.Integer(), nullable=True),
    sa.Column('poster_url', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_box_office_weekend_entries_region'), 'box_office_weekend_entries', ['region'], unique=False)
    op.create_table('box_office_ytd_top_movies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ytd_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('gross_usd', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['ytd_id'], ['box_office_ytd.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('box_office_ytd_top_movies')
    op.drop_index(op.f('ix_box_office_weekend_entries_region'), table_name='box_office_weekend_entries')
    op.drop_table('box_office_weekend_entries')
    op.drop_index(op.f('ix_box_office_ytd_year'), table_name='box_office_ytd')
    op.drop_index(op.f('ix_box_office_ytd_region'), table_name='box_office_ytd')
    op.drop_table('box_office_ytd')
    op.drop_index(op.f('ix_box_office_trends_region'), table_name='box_office_trends')
    op.drop_table('box_office_trends')
    op.drop_index(op.f('ix_box_office_records_region'), table_name='box_office_records')
    op.drop_table('box_office_records')
    op.drop_index(op.f('ix_box_office_perf_studio_region'), table_name='box_office_perf_studio')
    op.drop_table('box_office_perf_studio')
    op.drop_index(op.f('ix_box_office_perf_monthly_region'), table_name='box_office_perf_monthly')
    op.drop_table('box_office_perf_monthly')
    op.drop_index(op.f('ix_box_office_perf_genre_region'), table_name='box_office_perf_genre')
    op.drop_table('box_office_perf_genre')
    # ### end Alembic commands ###
