"""add_critic_platform_mvp_models

Revision ID: 5d063dcaa8ab
Revises: add_collection_likes
Create Date: 2025-11-06 17:44:01.275247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5d063dcaa8ab'
down_revision: Union[str, Sequence[str], None] = 'add_collection_likes'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('critic_affiliate_links',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('external_id', sa.String(length=50), nullable=False),
    sa.Column('critic_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('utm_source', sa.String(length=100), nullable=True),
    sa.Column('utm_medium', sa.String(length=100), nullable=True),
    sa.Column('utm_campaign', sa.String(length=100), nullable=True),
    sa.Column('click_count', sa.Integer(), nullable=False),
    sa.Column('conversion_count', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['critic_id'], ['critic_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_critic_affiliate_links_critic_id'), 'critic_affiliate_links', ['critic_id'], unique=False)
    op.create_index(op.f('ix_critic_affiliate_links_external_id'), 'critic_affiliate_links', ['external_id'], unique=True)
    op.create_table('critic_blog_posts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('external_id', sa.String(length=50), nullable=False),
    sa.Column('critic_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=250), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('excerpt', sa.String(length=500), nullable=True),
    sa.Column('cover_image_url', sa.String(length=255), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('like_count', sa.Integer(), nullable=False),
    sa.Column('comment_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['critic_id'], ['critic_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_critic_blog_posts_critic_id'), 'critic_blog_posts', ['critic_id'], unique=False)
    op.create_index(op.f('ix_critic_blog_posts_external_id'), 'critic_blog_posts', ['external_id'], unique=True)
    op.create_index(op.f('ix_critic_blog_posts_published_at'), 'critic_blog_posts', ['published_at'], unique=False)
    op.create_index(op.f('ix_critic_blog_posts_slug'), 'critic_blog_posts', ['slug'], unique=True)
    op.create_index(op.f('ix_critic_blog_posts_status'), 'critic_blog_posts', ['status'], unique=False)
    op.create_table('critic_brand_deals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('external_id', sa.String(length=50), nullable=False),
    sa.Column('critic_id', sa.Integer(), nullable=False),
    sa.Column('brand_name', sa.String(length=200), nullable=False),
    sa.Column('campaign_title', sa.String(length=200), nullable=False),
    sa.Column('brief', sa.Text(), nullable=False),
    sa.Column('rate_card', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('deliverables', sa.Text(), nullable=True),
    sa.Column('disclosure_required', sa.Boolean(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['critic_id'], ['critic_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_critic_brand_deals_critic_id'), 'critic_brand_deals', ['critic_id'], unique=False)
    op.create_index(op.f('ix_critic_brand_deals_external_id'), 'critic_brand_deals', ['external_id'], unique=True)
    op.create_index(op.f('ix_critic_brand_deals_status'), 'critic_brand_deals', ['status'], unique=False)
    op.create_table('critic_pinned_content',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('external_id', sa.String(length=50), nullable=False),
    sa.Column('critic_id', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.String(length=50), nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('pinned_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['critic_id'], ['critic_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_critic_pinned_content_critic_id'), 'critic_pinned_content', ['critic_id'], unique=False)
    op.create_index(op.f('ix_critic_pinned_content_external_id'), 'critic_pinned_content', ['external_id'], unique=True)
    op.create_table('critic_recommendations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('external_id', sa.String(length=50), nullable=False),
    sa.Column('critic_id', sa.Integer(), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('recommendation_type', sa.String(length=50), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['critic_id'], ['critic_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_critic_recommendations_created_at'), 'critic_recommendations', ['created_at'], unique=False)
    op.create_index(op.f('ix_critic_recommendations_critic_id'), 'critic_recommendations', ['critic_id'], unique=False)
    op.create_index(op.f('ix_critic_recommendations_external_id'), 'critic_recommendations', ['external_id'], unique=True)
    op.create_index(op.f('ix_critic_recommendations_movie_id'), 'critic_recommendations', ['movie_id'], unique=False)
    op.create_index(op.f('ix_critic_recommendations_recommendation_type'), 'critic_recommendations', ['recommendation_type'], unique=False)
    op.create_table('critic_sponsor_disclosures',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('external_id', sa.String(length=50), nullable=False),
    sa.Column('review_id', sa.Integer(), nullable=True),
    sa.Column('blog_post_id', sa.Integer(), nullable=True),
    sa.Column('brand_deal_id', sa.Integer(), nullable=True),
    sa.Column('disclosure_text', sa.Text(), nullable=False),
    sa.Column('disclosure_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['blog_post_id'], ['critic_blog_posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['brand_deal_id'], ['critic_brand_deals.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['review_id'], ['critic_reviews.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_critic_sponsor_disclosures_blog_post_id'), 'critic_sponsor_disclosures', ['blog_post_id'], unique=False)
    op.create_index(op.f('ix_critic_sponsor_disclosures_external_id'), 'critic_sponsor_disclosures', ['external_id'], unique=True)
    op.create_index(op.f('ix_critic_sponsor_disclosures_review_id'), 'critic_sponsor_disclosures', ['review_id'], unique=False)
    op.drop_constraint('feature_flags_feature_key_key', 'feature_flags', type_='unique')
    op.drop_index('idx_feature_flags_category', table_name='feature_flags')
    op.drop_index('idx_feature_flags_display_order', table_name='feature_flags')
    op.drop_index('idx_feature_flags_enabled', table_name='feature_flags')
    op.create_index(op.f('ix_feature_flags_category'), 'feature_flags', ['category'], unique=False)
    op.create_index(op.f('ix_feature_flags_display_order'), 'feature_flags', ['display_order'], unique=False)
    op.create_index(op.f('ix_feature_flags_feature_key'), 'feature_flags', ['feature_key'], unique=True)
    op.create_index(op.f('ix_feature_flags_id'), 'feature_flags', ['id'], unique=False)
    op.create_index(op.f('ix_feature_flags_is_enabled'), 'feature_flags', ['is_enabled'], unique=False)
    op.drop_index('ix_movies_awards_status', table_name='movies')
    op.drop_index('ix_movies_basic_info_status', table_name='movies')
    op.drop_index('ix_movies_cast_crew_status', table_name='movies')
    op.drop_index('ix_movies_media_status', table_name='movies')
    op.drop_index('ix_movies_streaming_status', table_name='movies')
    op.drop_index('ix_movies_timeline_status', table_name='movies')
    op.drop_index('ix_movies_trivia_status', table_name='movies')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_movies_trivia_status', 'movies', ['trivia_status'], unique=False)
    op.create_index('ix_movies_timeline_status', 'movies', ['timeline_status'], unique=False)
    op.create_index('ix_movies_streaming_status', 'movies', ['streaming_status'], unique=False)
    op.create_index('ix_movies_media_status', 'movies', ['media_status'], unique=False)
    op.create_index('ix_movies_cast_crew_status', 'movies', ['cast_crew_status'], unique=False)
    op.create_index('ix_movies_basic_info_status', 'movies', ['basic_info_status'], unique=False)
    op.create_index('ix_movies_awards_status', 'movies', ['awards_status'], unique=False)
    op.drop_index(op.f('ix_feature_flags_is_enabled'), table_name='feature_flags')
    op.drop_index(op.f('ix_feature_flags_id'), table_name='feature_flags')
    op.drop_index(op.f('ix_feature_flags_feature_key'), table_name='feature_flags')
    op.drop_index(op.f('ix_feature_flags_display_order'), table_name='feature_flags')
    op.drop_index(op.f('ix_feature_flags_category'), table_name='feature_flags')
    op.create_index('idx_feature_flags_enabled', 'feature_flags', ['is_enabled'], unique=False)
    op.create_index('idx_feature_flags_display_order', 'feature_flags', ['display_order'], unique=False)
    op.create_index('idx_feature_flags_category', 'feature_flags', ['category'], unique=False)
    op.create_unique_constraint('feature_flags_feature_key_key', 'feature_flags', ['feature_key'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_critic_sponsor_disclosures_review_id'), table_name='critic_sponsor_disclosures')
    op.drop_index(op.f('ix_critic_sponsor_disclosures_external_id'), table_name='critic_sponsor_disclosures')
    op.drop_index(op.f('ix_critic_sponsor_disclosures_blog_post_id'), table_name='critic_sponsor_disclosures')
    op.drop_table('critic_sponsor_disclosures')
    op.drop_index(op.f('ix_critic_recommendations_recommendation_type'), table_name='critic_recommendations')
    op.drop_index(op.f('ix_critic_recommendations_movie_id'), table_name='critic_recommendations')
    op.drop_index(op.f('ix_critic_recommendations_external_id'), table_name='critic_recommendations')
    op.drop_index(op.f('ix_critic_recommendations_critic_id'), table_name='critic_recommendations')
    op.drop_index(op.f('ix_critic_recommendations_created_at'), table_name='critic_recommendations')
    op.drop_table('critic_recommendations')
    op.drop_index(op.f('ix_critic_pinned_content_external_id'), table_name='critic_pinned_content')
    op.drop_index(op.f('ix_critic_pinned_content_critic_id'), table_name='critic_pinned_content')
    op.drop_table('critic_pinned_content')
    op.drop_index(op.f('ix_critic_brand_deals_status'), table_name='critic_brand_deals')
    op.drop_index(op.f('ix_critic_brand_deals_external_id'), table_name='critic_brand_deals')
    op.drop_index(op.f('ix_critic_brand_deals_critic_id'), table_name='critic_brand_deals')
    op.drop_table('critic_brand_deals')
    op.drop_index(op.f('ix_critic_blog_posts_status'), table_name='critic_blog_posts')
    op.drop_index(op.f('ix_critic_blog_posts_slug'), table_name='critic_blog_posts')
    op.drop_index(op.f('ix_critic_blog_posts_published_at'), table_name='critic_blog_posts')
    op.drop_index(op.f('ix_critic_blog_posts_external_id'), table_name='critic_blog_posts')
    op.drop_index(op.f('ix_critic_blog_posts_critic_id'), table_name='critic_blog_posts')
    op.drop_table('critic_blog_posts')
    op.drop_index(op.f('ix_critic_affiliate_links_external_id'), table_name='critic_affiliate_links')
    op.drop_index(op.f('ix_critic_affiliate_links_critic_id'), table_name='critic_affiliate_links')
    op.drop_table('critic_affiliate_links')
    # ### end Alembic commands ###
