"""add comprehensive movie fields and streaming platforms

Revision ID: b3bb728ade7b
Revises: 1a9c23c1eb8e
Create Date: 2025-10-18 19:19:37.909624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3bb728ade7b'
down_revision: Union[str, Sequence[str], None] = '1a9c23c1eb8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('streaming_platforms',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('external_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('logo_url', sa.String(length=255), nullable=True),
    sa.Column('website_url', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_streaming_platforms_external_id'), 'streaming_platforms', ['external_id'], unique=True)
    op.create_table('movie_streaming_options',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('external_id', sa.String(length=80), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('platform_id', sa.Integer(), nullable=False),
    sa.Column('region', sa.String(length=10), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('price', sa.String(length=20), nullable=True),
    sa.Column('quality', sa.String(length=10), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ),
    sa.ForeignKeyConstraint(['platform_id'], ['streaming_platforms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movie_streaming_options_external_id'), 'movie_streaming_options', ['external_id'], unique=True)
    op.create_index(op.f('ix_movie_streaming_options_region'), 'movie_streaming_options', ['region'], unique=False)
    op.add_column('movies', sa.Column('tagline', sa.String(length=500), nullable=True))
    op.add_column('movies', sa.Column('release_date', sa.DateTime(), nullable=True))
    op.add_column('movies', sa.Column('critics_score', sa.Float(), nullable=True))
    op.add_column('movies', sa.Column('imdb_rating', sa.Float(), nullable=True))
    op.add_column('movies', sa.Column('rotten_tomatoes_score', sa.Integer(), nullable=True))
    op.add_column('movies', sa.Column('rating', sa.String(length=10), nullable=True))
    op.add_column('movies', sa.Column('backdrop_url', sa.String(length=255), nullable=True))
    op.add_column('movies', sa.Column('budget', sa.Integer(), nullable=True))
    op.add_column('movies', sa.Column('revenue', sa.Integer(), nullable=True))
    op.add_column('movies', sa.Column('status', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movies', 'status')
    op.drop_column('movies', 'revenue')
    op.drop_column('movies', 'budget')
    op.drop_column('movies', 'backdrop_url')
    op.drop_column('movies', 'rating')
    op.drop_column('movies', 'rotten_tomatoes_score')
    op.drop_column('movies', 'imdb_rating')
    op.drop_column('movies', 'critics_score')
    op.drop_column('movies', 'release_date')
    op.drop_column('movies', 'tagline')
    op.drop_index(op.f('ix_movie_streaming_options_region'), table_name='movie_streaming_options')
    op.drop_index(op.f('ix_movie_streaming_options_external_id'), table_name='movie_streaming_options')
    op.drop_table('movie_streaming_options')
    op.drop_index(op.f('ix_streaming_platforms_external_id'), table_name='streaming_platforms')
    op.drop_table('streaming_platforms')
    # ### end Alembic commands ###
