"""add people and movie fields

Revision ID: b9da3f589139
Revises: 453f540df1cd
Create Date: 2025-10-18 12:56:12.224659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9da3f589139'
down_revision: Union[str, Sequence[str], None] = '453f540df1cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('people',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('external_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_people_external_id'), 'people', ['external_id'], unique=True)
    op.create_table('movie_people',
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('character_name', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ),
    sa.PrimaryKeyConstraint('movie_id', 'person_id')
    )
    op.add_column('movies', sa.Column('year', sa.String(length=4), nullable=True))
    op.add_column('movies', sa.Column('runtime', sa.Integer(), nullable=True))
    op.add_column('movies', sa.Column('siddu_score', sa.Float(), nullable=True))
    op.add_column('movies', sa.Column('language', sa.String(length=50), nullable=True))
    op.add_column('movies', sa.Column('country', sa.String(length=50), nullable=True))
    op.add_column('movies', sa.Column('overview', sa.Text(), nullable=True))
    op.add_column('movies', sa.Column('poster_url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movies', 'poster_url')
    op.drop_column('movies', 'overview')
    op.drop_column('movies', 'country')
    op.drop_column('movies', 'language')
    op.drop_column('movies', 'siddu_score')
    op.drop_column('movies', 'runtime')
    op.drop_column('movies', 'year')
    op.drop_table('movie_people')
    op.drop_index(op.f('ix_people_external_id'), table_name='people')
    op.drop_table('people')
    # ### end Alembic commands ###
