"""add trivia and timeline JSONB fields to movies

Revision ID: df12a3b9a6c1
Revises: b3bb728ade7b
Create Date: 2025-10-18 21:35:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "df12a3b9a6c1"
down_revision: Union[str, Sequence[str], None] = "b3bb728ade7b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("movies", sa.Column("trivia", postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column("movies", sa.Column("timeline", postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("movies", "timeline")
    op.drop_column("movies", "trivia")
    # ### end Alembic commands ###

