"""add admin domain

Revision ID: f3cc9a6f162c
Revises: f313c39a8c93
Create Date: 2025-10-18 16:32:16.847973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f3cc9a6f162c'
down_revision: Union[str, Sequence[str], None] = 'f313c39a8c93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_metric_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('snapshot_time', sa.DateTime(), nullable=False),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_metric_snapshots_snapshot_time'), 'admin_metric_snapshots', ['snapshot_time'], unique=False)
    op.create_table('system_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('external_id', sa.String(length=40), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_settings_external_id'), 'system_settings', ['external_id'], unique=True)
    op.create_table('admin_user_meta',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('roles', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('joined_date', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('profile_type', sa.String(length=40), nullable=True),
    sa.Column('verification_status', sa.String(length=20), nullable=True),
    sa.Column('account_type', sa.String(length=40), nullable=True),
    sa.Column('phone_number', sa.String(length=40), nullable=True),
    sa.Column('location', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_user_meta_email'), 'admin_user_meta', ['email'], unique=False)
    op.create_index(op.f('ix_admin_user_meta_status'), 'admin_user_meta', ['status'], unique=False)
    op.create_index(op.f('ix_admin_user_meta_user_id'), 'admin_user_meta', ['user_id'], unique=True)
    op.create_table('moderation_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('external_id', sa.String(length=80), nullable=False),
    sa.Column('content_type', sa.String(length=20), nullable=False),
    sa.Column('content_title', sa.String(length=255), nullable=False),
    sa.Column('report_reason', sa.String(length=120), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reporter_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('content_ref', sa.String(length=80), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_moderation_items_content_type'), 'moderation_items', ['content_type'], unique=False)
    op.create_index(op.f('ix_moderation_items_created_at'), 'moderation_items', ['created_at'], unique=False)
    op.create_index(op.f('ix_moderation_items_external_id'), 'moderation_items', ['external_id'], unique=True)
    op.create_index(op.f('ix_moderation_items_status'), 'moderation_items', ['status'], unique=False)
    op.create_table('moderation_actions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('moderator_user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['moderation_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['moderator_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_moderation_actions_item_id'), 'moderation_actions', ['item_id'], unique=False)
    op.create_index(op.f('ix_moderation_actions_moderator_user_id'), 'moderation_actions', ['moderator_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_moderation_actions_moderator_user_id'), table_name='moderation_actions')
    op.drop_index(op.f('ix_moderation_actions_item_id'), table_name='moderation_actions')
    op.drop_table('moderation_actions')
    op.drop_index(op.f('ix_moderation_items_status'), table_name='moderation_items')
    op.drop_index(op.f('ix_moderation_items_external_id'), table_name='moderation_items')
    op.drop_index(op.f('ix_moderation_items_created_at'), table_name='moderation_items')
    op.drop_index(op.f('ix_moderation_items_content_type'), table_name='moderation_items')
    op.drop_table('moderation_items')
    op.drop_index(op.f('ix_admin_user_meta_user_id'), table_name='admin_user_meta')
    op.drop_index(op.f('ix_admin_user_meta_status'), table_name='admin_user_meta')
    op.drop_index(op.f('ix_admin_user_meta_email'), table_name='admin_user_meta')
    op.drop_table('admin_user_meta')
    op.drop_index(op.f('ix_system_settings_external_id'), table_name='system_settings')
    op.drop_table('system_settings')
    op.drop_index(op.f('ix_admin_metric_snapshots_snapshot_time'), table_name='admin_metric_snapshots')
    op.drop_table('admin_metric_snapshots')
    # ### end Alembic commands ###
