/**
 * Mock Trending Movies Data
 * 10 trending movies
 */

import { TrendingMovie } from '@/types/pulse'

export const mockTrendingMovies: TrendingMovie[] = [
  {
    id: 'trending-movie-1',
    title: 'The Shawshank Redemption',
    year: 1994,
    poster_url: 'https://image.tmdb.org/t/p/w500/q6y0Go1tsGEsmtFryDOJo3dEmqu.jpg',
    rating: 9.3,
    genre: 'Drama',
    pulse_count: 3456,
    trend_rank: 1,
  },
  {
    id: 'trending-movie-2',
    title: 'Oppenheimer',
    year: 2023,
    poster_url: 'https://image.tmdb.org/t/p/w500/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg',
    rating: 8.5,
    genre: 'Biography',
    pulse_count: 2890,
    trend_rank: 2,
  },
  {
    id: 'trending-movie-3',
    title: 'The Dark Knight',
    year: 2008,
    poster_url: 'https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
    rating: 9.0,
    genre: 'Action',
    pulse_count: 2345,
    trend_rank: 3,
  },
  {
    id: 'trending-movie-4',
    title: 'Inception',
    year: 2010,
    poster_url: 'https://image.tmdb.org/t/p/w500/9gk7adHYeDvHkCSEqAvQNLV5Uge.jpg',
    rating: 8.8,
    genre: 'Sci-Fi',
    pulse_count: 1890,
    trend_rank: 4,
  },
  {
    id: 'trending-movie-5',
    title: 'Parasite',
    year: 2019,
    poster_url: 'https://image.tmdb.org/t/p/w500/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg',
    rating: 8.6,
    genre: 'Thriller',
    pulse_count: 1567,
    trend_rank: 5,
  },
  {
    id: 'trending-movie-6',
    title: 'Interstellar',
    year: 2014,
    poster_url: 'https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg',
    rating: 8.7,
    genre: 'Sci-Fi',
    pulse_count: 1234,
    trend_rank: 6,
  },
  {
    id: 'trending-movie-7',
    title: 'The Godfather',
    year: 1972,
    poster_url: 'https://image.tmdb.org/t/p/w500/3bhkrj58Vtu7enYsRolD1fZdja1.jpg',
    rating: 9.2,
    genre: 'Crime',
    pulse_count: 1123,
    trend_rank: 7,
  },
  {
    id: 'trending-movie-8',
    title: 'Pulp Fiction',
    year: 1994,
    poster_url: 'https://image.tmdb.org/t/p/w500/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg',
    rating: 8.9,
    genre: 'Crime',
    pulse_count: 987,
    trend_rank: 8,
  },
  {
    id: 'trending-movie-9',
    title: 'Forrest Gump',
    year: 1994,
    poster_url: 'https://image.tmdb.org/t/p/w500/arw2vcBveWOVZr6pxd9XTd1TdQa.jpg',
    rating: 8.8,
    genre: 'Drama',
    pulse_count: 876,
    trend_rank: 9,
  },
  {
    id: 'trending-movie-10',
    title: 'The Matrix',
    year: 1999,
    poster_url: 'https://image.tmdb.org/t/p/w500/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg',
    rating: 8.7,
    genre: 'Sci-Fi',
    pulse_count: 765,
    trend_rank: 10,
  },
]

