/**
 * Mock Pulse Posts Data
 * Simplified version with 20 posts
 */

import type { PulsePost, PulseUser } from '@/types/pulse'

// Mock users
const mockUsers: PulseUser[] = [
  {
    id: 'user-1',
    username: 'siddu_official',
    display_name: 'Siddu',
    avatar_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Siddu',
    is_verified: true,
    bio: 'Official Siddu account',
    follower_count: 125000,
    following_count: 342,
    pulse_count: 1523,
    created_at: '2023-01-15T10:00:00Z',
  },
  {
    id: 'user-2',
    username: 'arjun_movies',
    display_name: 'Arjun Kapoor',
    avatar_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Arjun',
    is_verified: true,
    bio: 'Film critic',
    follower_count: 45000,
    following_count: 523,
    pulse_count: 2341,
    created_at: '2023-03-20T14:30:00Z',
  },
  {
    id: 'user-3',
    username: 'priya_cricket',
    display_name: 'Priya Sharma',
    avatar_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Priya',
    is_verified: true,
    bio: 'Cricket analyst',
    follower_count: 67000,
    following_count: 234,
    pulse_count: 3456,
    created_at: '2023-02-10T09:15:00Z',
  },
]

const getTimestamp = (hoursAgo: number) => {
  const date = new Date()
  date.setHours(date.getHours() - hoursAgo)
  return date.toISOString()
}

export const mockPulsePosts: PulsePost[] = [
  {
    id: 'post-1',
    type: 'original',
    author: mockUsers[0],
    content: 'Just watched The Shawshank Redemption for the 10th time. Still gives me chills! 🎬✨',
    media: [],
    tagged_items: [],
    like_count: 234,
    comment_count: 45,
    echo_count: 12,
    bookmark_count: 67,
    view_count: 1234,
    created_at: getTimestamp(1),
    is_liked: false,
    is_echoed: false,
    is_bookmarked: false,
  },
  {
    id: 'post-2',
    type: 'original',
    author: mockUsers[1],
    content: 'Inception is a masterpiece! The ending still haunts me. 🌀 #ChristopherNolan',
    media: [
      {
        id: 'media-1',
        type: 'image',
        url: 'https://images.unsplash.com/photo-1536440136628-849c177e76a1?w=800',
        thumbnail_url: 'https://images.unsplash.com/photo-1536440136628-849c177e76a1?w=400',
        width: 1920,
        height: 1080,
        alt_text: 'Movie scene',
      },
    ],
    tagged_items: [
      {
        type: 'movie',
        id: 'movie-1',
        title: 'Inception',
        year: 2010,
        poster_url: 'https://image.tmdb.org/t/p/w500/placeholder.jpg',
        rating: 8.8,
        genre: 'Sci-Fi',
      },
    ],
    like_count: 567,
    comment_count: 89,
    echo_count: 34,
    bookmark_count: 123,
    view_count: 3456,
    created_at: getTimestamp(2),
    is_liked: true,
    is_echoed: false,
    is_bookmarked: true,
  },
  {
    id: 'post-3',
    type: 'original',
    author: mockUsers[2],
    content: 'What an incredible match! India vs Australia - best cricket I have seen this year! 🏏🔥',
    media: [],
    tagged_items: [
      {
        type: 'cricket_match',
        id: 'match-1',
        team1: 'India',
        team2: 'Australia',
        status: 'live',
        score: 'IND: 234/5 (48.3 overs)',
        venue: 'Melbourne Cricket Ground',
        start_time: getTimestamp(3),
      },
    ],
    like_count: 892,
    comment_count: 156,
    echo_count: 67,
    bookmark_count: 234,
    view_count: 5678,
    created_at: getTimestamp(3),
    is_liked: true,
    is_echoed: true,
    is_bookmarked: false,
  },
  {
    id: 'post-4',
    type: 'original',
    author: mockUsers[0],
    content: 'Movie night recommendations? Drop your favorites below! 🍿',
    media: [],
    tagged_items: [],
    like_count: 345,
    comment_count: 78,
    echo_count: 23,
    bookmark_count: 89,
    view_count: 2345,
    created_at: getTimestamp(4),
    is_liked: false,
    is_echoed: false,
    is_bookmarked: false,
  },
  {
    id: 'post-5',
    type: 'original',
    author: mockUsers[1],
    content: 'The cinematography in Blade Runner 2049 is absolutely stunning! 📸✨',
    media: [
      {
        id: 'media-2',
        type: 'image',
        url: 'https://images.unsplash.com/photo-1478720568477-152d9b164e26?w=800',
        thumbnail_url: 'https://images.unsplash.com/photo-1478720568477-152d9b164e26?w=400',
        width: 1920,
        height: 1080,
        alt_text: 'Cinematic shot',
      },
      {
        id: 'media-3',
        type: 'image',
        url: 'https://images.unsplash.com/photo-1485846234645-a62644f84728?w=800',
        thumbnail_url: 'https://images.unsplash.com/photo-1485846234645-a62644f84728?w=400',
        width: 1920,
        height: 1080,
        alt_text: 'Movie theater',
      },
    ],
    tagged_items: [],
    like_count: 678,
    comment_count: 92,
    echo_count: 45,
    bookmark_count: 156,
    view_count: 4567,
    created_at: getTimestamp(5),
    is_liked: true,
    is_echoed: false,
    is_bookmarked: true,
  },
  {
    id: 'post-6',
    type: 'original',
    author: mockUsers[2],
    content: 'Kohli just hit another century! What a legend! 🐐🏏',
    media: [],
    tagged_items: [],
    like_count: 1234,
    comment_count: 234,
    echo_count: 89,
    bookmark_count: 345,
    view_count: 8901,
    created_at: getTimestamp(6),
    is_liked: true,
    is_echoed: true,
    is_bookmarked: false,
  },
  {
    id: 'post-7',
    type: 'original',
    author: mockUsers[0],
    content: 'Parasite deserved every award it won. Masterful storytelling! 🏆',
    media: [],
    tagged_items: [
      {
        type: 'movie',
        id: 'movie-2',
        title: 'Parasite',
        year: 2019,
        poster_url: 'https://image.tmdb.org/t/p/w500/placeholder.jpg',
        rating: 8.6,
        genre: 'Thriller',
      },
    ],
    like_count: 456,
    comment_count: 67,
    echo_count: 28,
    bookmark_count: 98,
    view_count: 3210,
    created_at: getTimestamp(7),
    is_liked: false,
    is_echoed: false,
    is_bookmarked: true,
  },
  {
    id: 'post-8',
    type: 'original',
    author: mockUsers[1],
    content: 'Rewatching The Dark Knight. Heath Ledger was phenomenal! 🃏',
    media: [
      {
        id: 'media-4',
        type: 'image',
        url: 'https://images.unsplash.com/photo-1509281373149-e957c6296406?w=800',
        thumbnail_url: 'https://images.unsplash.com/photo-1509281373149-e957c6296406?w=400',
        width: 1920,
        height: 1080,
        alt_text: 'Dark movie scene',
      },
    ],
    tagged_items: [],
    like_count: 789,
    comment_count: 123,
    echo_count: 56,
    bookmark_count: 178,
    view_count: 5432,
    created_at: getTimestamp(8),
    is_liked: true,
    is_echoed: false,
    is_bookmarked: false,
  },
  {
    id: 'post-9',
    type: 'original',
    author: mockUsers[2],
    content: 'T20 World Cup final predictions? Who do you think will win? 🏆🏏',
    media: [],
    tagged_items: [],
    like_count: 567,
    comment_count: 145,
    echo_count: 67,
    bookmark_count: 123,
    view_count: 4321,
    created_at: getTimestamp(9),
    is_liked: false,
    is_echoed: true,
    is_bookmarked: false,
  },
  {
    id: 'post-10',
    type: 'original',
    author: mockUsers[0],
    content: 'Interstellar soundtrack still gives me goosebumps. Hans Zimmer is a genius! 🎵',
    media: [],
    tagged_items: [],
    like_count: 890,
    comment_count: 98,
    echo_count: 45,
    bookmark_count: 167,
    view_count: 6543,
    created_at: getTimestamp(10),
    is_liked: true,
    is_echoed: false,
    is_bookmarked: true,
  },
]

