import type { WatchlistItem } from "./types"

export const mockWatchlistItems: WatchlistItem[] = [
  {
    id: "1",
    title: "Inception",
    posterUrl: "/inception-movie-poster.png",
    backdropUrl: "/dark-blue-city-skyline.png",
    dateAdded: "2023-12-15",
    releaseDate: "2010-07-16",
    status: "want-to-watch",
    priority: "high",
    rating: 8.8,
    genres: ["Sci-Fi", "Action", "Thriller"],
    runtime: 148,
    director: "Christopher Nolan",
    streamingServices: ["netflix", "amazon-prime", "hbo-max"],
  },
  {
    id: "2",
    title: "Parasite",
    posterUrl: "/parasite-movie-poster.png",
    dateAdded: "2023-11-20",
    releaseDate: "2019-05-30",
    status: "want-to-watch",
    priority: "medium",
    rating: 8.6,
    genres: ["Thriller", "Drama", "Comedy"],
    runtime: 132,
    director: "Bong Joon-ho",
    streamingServices: ["hulu", "amazon-prime"],
  },
  {
    id: "3",
    title: "The Dark Knight",
    posterUrl: "/dark-knight-poster.png",
    dateAdded: "2023-10-05",
    releaseDate: "2008-07-18",
    status: "watching",
    priority: "high",
    progress: 65,
    rating: 9.0,
    genres: ["Action", "Crime", "Drama"],
    runtime: 152,
    director: "Christopher Nolan",
    streamingServices: ["hbo-max", "netflix"],
  },
  {
    id: "4",
    title: "Pulp Fiction",
    posterUrl: "/pulp-fiction-poster.png",
    dateAdded: "2023-09-12",
    releaseDate: "1994-10-14",
    status: "watching",
    priority: "medium",
    progress: 30,
    rating: 8.9,
    genres: ["Crime", "Drama"],
    runtime: 154,
    director: "Quentin Tarantino",
    streamingServices: ["netflix", "amazon-prime"],
  },
  {
    id: "5",
    title: "Dune",
    posterUrl: "/dune-part-two-poster.png",
    dateAdded: "2024-01-10",
    releaseDate: "2021-10-22",
    status: "want-to-watch",
    priority: "high",
    rating: 8.0,
    genres: ["Sci-Fi", "Adventure"],
    runtime: 155,
    director: "Denis Villeneuve",
    streamingServices: ["hbo-max"],
  },
  {
    id: "6",
    title: "Oppenheimer",
    posterUrl: "/oppenheimer-inspired-poster.png",
    backdropUrl: "/dramatic-oppenheimer.png",
    dateAdded: "2023-08-15",
    releaseDate: "2023-07-21",
    status: "want-to-watch",
    priority: "low",
    rating: 8.5,
    genres: ["Biography", "Drama", "History"],
    runtime: 180,
    director: "Christopher Nolan",
    streamingServices: ["amazon-prime"],
  },
  {
    id: "7",
    title: "The Shawshank Redemption",
    posterUrl: "/shawshank-redemption-poster.png",
    dateAdded: "2023-07-22",
    releaseDate: "1994-09-23",
    status: "watched",
    priority: "low",
    rating: 9.3,
    genres: ["Drama"],
    runtime: 142,
    director: "Frank Darabont",
    streamingServices: ["netflix", "hulu"],
  },
  {
    id: "8",
    title: "Interstellar",
    posterUrl: "/interstellar-poster.png",
    dateAdded: "2023-06-18",
    releaseDate: "2014-11-07",
    status: "watched",
    priority: "medium",
    rating: 8.6,
    genres: ["Adventure", "Drama", "Sci-Fi"],
    runtime: 169,
    director: "Christopher Nolan",
    streamingServices: ["netflix", "paramount"],
  },
  {
    id: "9",
    title: "Fight Club",
    posterUrl: "/fight-club-poster.png",
    dateAdded: "2023-05-30",
    releaseDate: "1999-10-15",
    status: "watched",
    priority: "high",
    rating: 8.8,
    genres: ["Drama"],
    runtime: 139,
    director: "David Fincher",
    streamingServices: ["hulu", "disney-plus"],
  },
  {
    id: "10",
    title: "The Matrix",
    posterUrl: "/matrix-poster.png",
    dateAdded: "2023-04-12",
    releaseDate: "1999-03-31",
    status: "watched",
    priority: "medium",
    rating: 8.7,
    genres: ["Action", "Sci-Fi"],
    runtime: 136,
    director: "Lana Wachowski, Lilly Wachowski",
    streamingServices: ["hbo-max", "netflix"],
  },
  {
    id: "11",
    title: "Barbie",
    posterUrl: "/barbie-movie-poster.png",
    backdropUrl: "/vibrant-pink-dreamhouse.png",
    dateAdded: "2024-02-05",
    releaseDate: "2023-07-21",
    status: "want-to-watch",
    priority: "medium",
    rating: 7.0,
    genres: ["Adventure", "Comedy", "Fantasy"],
    runtime: 114,
    director: "Greta Gerwig",
    streamingServices: ["hbo-max", "amazon-prime"],
  },
  {
    id: "12",
    title: "Poor Things",
    posterUrl: "/poor-things-poster.png",
    dateAdded: "2024-01-28",
    releaseDate: "2023-12-08",
    status: "want-to-watch",
    priority: "high",
    rating: 8.4,
    genres: ["Romance", "Sci-Fi", "Comedy"],
    runtime: 141,
    director: "Yorgos Lanthimos",
    streamingServices: ["hulu"],
  },
  {
    id: "13",
    title: "The Godfather",
    posterUrl: "/classic-mob-poster.png",
    dateAdded: "2023-03-15",
    releaseDate: "1972-03-24",
    status: "watched",
    priority: "low",
    rating: 9.2,
    genres: ["Crime", "Drama"],
    runtime: 175,
    director: "Francis Ford Coppola",
    streamingServices: ["paramount", "netflix"],
  },
  {
    id: "14",
    title: "Challengers",
    posterUrl: "/challengers-poster.png",
    dateAdded: "2024-02-10",
    releaseDate: "2024-04-26",
    status: "want-to-watch",
    priority: "medium",
    rating: 7.8,
    genres: ["Drama", "Sport", "Romance"],
    runtime: 131,
    director: "Luca Guadagnino",
    streamingServices: ["amazon-prime"],
  },
  {
    id: "15",
    title: "Killers of the Flower Moon",
    posterUrl: "/killers-of-the-flower-moon-poster.png",
    dateAdded: "2023-12-05",
    releaseDate: "2023-10-20",
    status: "watching",
    priority: "high",
    progress: 45,
    rating: 7.7,
    genres: ["Crime", "Drama", "History"],
    runtime: 206,
    director: "Martin Scorsese",
    streamingServices: ["apple-tv", "amazon-prime"],
  },
  {
    id: "16",
    title: "Asteroid City",
    posterUrl: "/asteroid-city-poster.png",
    dateAdded: "2023-11-10",
    releaseDate: "2023-06-16",
    status: "watching",
    priority: "low",
    progress: 80,
    rating: 6.6,
    genres: ["Comedy", "Drama", "Romance"],
    runtime: 105,
    director: "Wes Anderson",
    streamingServices: ["apple-tv", "amazon-prime"],
  },
]
