import type { TeamProfile } from "./types"

export const getMockTeamData = (id: string): TeamProfile => {
  // This would normally fetch from an API, but for demo purposes we'll return mock data
  return {
    id,
    name: "India",
    shortName: "IND",
    established: "1932",
    logoUrl: "/cricket/india-logo.png",
    homeGround: "Eden Gardens, Kolkata",
    captain: "Rohit Sharma",
    coach: "Rahul Dravid",
    formats: ["Test", "ODI", "T20I"],
    teamColors: {
      primary: "#0033A0",
      secondary: "#FF9933",
    },
    iccRanking: {
      test: 1,
      odi: 2,
      t20: 1,
    },
    players: [
      {
        id: "virat-kohli",
        name: "Virat Kohli",
        role: "Batsman",
        battingStyle: "Right-handed",
        bowlingStyle: "Right-arm medium",
        age: 35,
        imageUrl: "/cricket/virat-kohli.png",
      },
      {
        id: "rohit-sharma",
        name: "Rohit Sharma",
        role: "Batsman",
        battingStyle: "Right-handed",
        bowlingStyle: "Right-arm off break",
        age: 36,
        imageUrl: "/rohit-sharma-cricketer.png",
      },
      {
        id: "jasprit-bumrah",
        name: "Jasprit Bumrah",
        role: "Bowler",
        battingStyle: "Right-handed",
        bowlingStyle: "Right-arm fast",
        age: 30,
        imageUrl: "/jasprit-bumrah-cricketer.png",
      },
      {
        id: "ravindra-jadeja",
        name: "Ravindra Jadeja",
        role: "All-rounder",
        battingStyle: "Left-handed",
        bowlingStyle: "Left-arm orthodox",
        age: 35,
        imageUrl: "/ravindra-jadeja-cricketer.png",
      },
      {
        id: "kl-rahul",
        name: "KL Rahul",
        role: "Wicket-keeper",
        battingStyle: "Right-handed",
        age: 32,
        imageUrl: "/placeholder.svg?height=300&width=300&query=KL Rahul cricketer",
      },
      {
        id: "rishabh-pant",
        name: "Rishabh Pant",
        role: "Wicket-keeper",
        battingStyle: "Left-handed",
        age: 26,
        imageUrl: "/placeholder.svg?height=300&width=300&query=Rishabh Pant cricketer",
      },
      {
        id: "hardik-pandya",
        name: "Hardik Pandya",
        role: "All-rounder",
        battingStyle: "Right-handed",
        bowlingStyle: "Right-arm medium-fast",
        age: 30,
        imageUrl: "/placeholder.svg?height=300&width=300&query=Hardik Pandya cricketer",
      },
      {
        id: "ravichandran-ashwin",
        name: "Ravichandran Ashwin",
        role: "Bowler",
        battingStyle: "Right-handed",
        bowlingStyle: "Right-arm off-break",
        age: 38,
        imageUrl: "/placeholder.svg?height=300&width=300&query=Ravichandran Ashwin cricketer",
      },
      {
        id: "mohammed-shami",
        name: "Mohammed Shami",
        role: "Bowler",
        battingStyle: "Right-handed",
        bowlingStyle: "Right-arm fast",
        age: 33,
        imageUrl: "/placeholder.svg?height=300&width=300&query=Mohammed Shami cricketer",
      },
      {
        id: "shubman-gill",
        name: "Shubman Gill",
        role: "Batsman",
        battingStyle: "Right-handed",
        age: 24,
        imageUrl: "/placeholder.svg?height=300&width=300&query=Shubman Gill cricketer",
      },
    ],
    recentMatches: [
      {
        id: "match1",
        date: "2023-11-15",
        format: "ODI",
        opponent: {
          id: "aus",
          name: "Australia",
          logoUrl: "/cricket/australia-logo.png",
        },
        venue: "Mumbai, India",
        result: "India won by 5 wickets",
        scorecard: {
          team: "269/5",
          opponent: "265/10",
        },
      },
      {
        id: "match2",
        date: "2023-11-10",
        format: "ODI",
        opponent: {
          id: "aus",
          name: "Australia",
          logoUrl: "/cricket/australia-logo.png",
        },
        venue: "Delhi, India",
        result: "Australia won by 3 wickets",
        scorecard: {
          team: "245/10",
          opponent: "248/7",
        },
      },
      {
        id: "match3",
        date: "2023-11-05",
        format: "ODI",
        opponent: {
          id: "nz",
          name: "New Zealand",
          logoUrl: "/cricket/new-zealand-logo.png",
        },
        venue: "Chennai, India",
        result: "India won by 7 wickets",
        scorecard: {
          team: "275/3",
          opponent: "273/8",
        },
      },
    ],
    upcomingMatches: [
      {
        id: "match4",
        date: "2023-12-05",
        format: "Test",
        opponent: {
          id: "eng",
          name: "England",
          logoUrl: "/cricket/england-logo.png",
        },
        venue: "Chennai, India",
        result: "Upcoming",
        scorecard: {
          team: "",
          opponent: "",
        },
      },
      {
        id: "match5",
        date: "2023-12-13",
        format: "Test",
        opponent: {
          id: "eng",
          name: "England",
          logoUrl: "/cricket/england-logo.png",
        },
        venue: "Mumbai, India",
        result: "Upcoming",
        scorecard: {
          team: "",
          opponent: "",
        },
      },
      {
        id: "match6",
        date: "2023-12-21",
        format: "Test",
        opponent: {
          id: "eng",
          name: "England",
          logoUrl: "/cricket/england-logo.png",
        },
        venue: "Ahmedabad, India",
        result: "Upcoming",
        scorecard: {
          team: "",
          opponent: "",
        },
      },
    ],
    trophies: [
      {
        id: "trophy1",
        name: "ICC Cricket World Cup",
        year: "2011",
        imageUrl: "/placeholder.svg?height=200&width=200&query=Cricket World Cup Trophy",
        description: "Champions of the 2011 ICC Cricket World Cup, defeating Sri Lanka in the final.",
      },
      {
        id: "trophy2",
        name: "ICC T20 World Cup",
        year: "2007",
        imageUrl: "/placeholder.svg?height=200&width=200&query=T20 World Cup Trophy",
        description: "Champions of the inaugural ICC T20 World Cup, defeating Pakistan in the final.",
      },
      {
        id: "trophy3",
        name: "ICC Champions Trophy",
        year: "2013",
        imageUrl: "/placeholder.svg?height=200&width=200&query=Champions Trophy Cricket",
        description: "Champions of the 2013 ICC Champions Trophy, defeating England in the final.",
      },
      {
        id: "trophy4",
        name: "Border-Gavaskar Trophy",
        year: "2020-21",
        imageUrl: "/placeholder.svg?height=200&width=200&query=Border Gavaskar Trophy",
        description: "Retained the Border-Gavaskar Trophy with a historic 2-1 series win in Australia.",
      },
    ],
    statistics: {
      overall: {
        matches: 1152,
        wins: 594,
        losses: 426,
        draws: 132,
        winPercentage: 51.56,
        highestScore: "418/5",
        lowestScore: "36/10",
        venuePerformance: {
          "Eden Gardens": 72,
          "Wankhede Stadium": 68,
          "M. Chinnaswamy Stadium": 65,
          "MA Chidambaram Stadium": 70,
          "Narendra Modi Stadium": 75,
        },
        rivalRecords: {
          Australia: {
            wins: 86,
            losses: 95,
            draws: 28,
          },
          England: {
            wins: 94,
            losses: 102,
            draws: 58,
          },
          Pakistan: {
            wins: 73,
            losses: 86,
            draws: 12,
          },
          "South Africa": {
            wins: 65,
            losses: 53,
            draws: 14,
          },
          "West Indies": {
            wins: 88,
            losses: 64,
            draws: 16,
          },
        },
      },
      formats: {
        test: {
          matches: 563,
          wins: 173,
          losses: 173,
          draws: 217,
          winPercentage: 30.73,
          highestScore: "759/7d",
          lowestScore: "36/10",
          venuePerformance: {
            "Eden Gardens": 75,
            "Wankhede Stadium": 70,
            "M. Chinnaswamy Stadium": 65,
            "MA Chidambaram Stadium": 72,
            "Narendra Modi Stadium": 78,
          },
          rivalRecords: {
            Australia: {
              wins: 32,
              losses: 43,
              draws: 28,
            },
            England: {
              wins: 35,
              losses: 50,
              draws: 49,
            },
            Pakistan: {
              wins: 9,
              losses: 12,
              draws: 38,
            },
            "South Africa": {
              wins: 15,
              losses: 16,
              draws: 12,
            },
            "West Indies": {
              wins: 23,
              losses: 30,
              draws: 46,
            },
          },
        },
        odi: {
          matches: 1011,
          wins: 518,
          losses: 443,
          draws: 50,
          winPercentage: 51.24,
          highestScore: "418/5",
          lowestScore: "54/10",
          venuePerformance: {
            "Eden Gardens": 70,
            "Wankhede Stadium": 65,
            "M. Chinnaswamy Stadium": 68,
            "MA Chidambaram Stadium": 72,
            "Narendra Modi Stadium": 75,
          },
          rivalRecords: {
            Australia: {
              wins: 53,
              losses: 80,
              draws: 10,
            },
            England: {
              wins: 55,
              losses: 43,
              draws: 3,
            },
            Pakistan: {
              wins: 55,
              losses: 73,
              draws: 4,
            },
            "South Africa": {
              wins: 35,
              losses: 46,
              draws: 3,
            },
            "West Indies": {
              wins: 65,
              losses: 63,
              draws: 2,
            },
          },
        },
        t20: {
          matches: 178,
          wins: 113,
          losses: 57,
          draws: 8,
          winPercentage: 63.48,
          highestScore: "260/5",
          lowestScore: "74/10",
          venuePerformance: {
            "Eden Gardens": 68,
            "Wankhede Stadium": 72,
            "M. Chinnaswamy Stadium": 70,
            "MA Chidambaram Stadium": 65,
            "Narendra Modi Stadium": 75,
          },
          rivalRecords: {
            Australia: {
              wins: 14,
              losses: 9,
              draws: 1,
            },
            England: {
              wins: 12,
              losses: 10,
              draws: 1,
            },
            Pakistan: {
              wins: 8,
              losses: 3,
              draws: 0,
            },
            "South Africa": {
              wins: 12,
              losses: 9,
              draws: 1,
            },
            "West Indies": {
              wins: 15,
              losses: 7,
              draws: 1,
            },
          },
        },
      },
    },
  }
}

export const mockTeamIds = ["india", "australia", "england", "south-africa", "new-zealand", "pakistan"]
