"""add festivals domain

Revision ID: 36c9dd3161ab
Revises: 4f6f1d334794
Create Date: 2025-10-18 14:19:01.133973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36c9dd3161ab'
down_revision: Union[str, Sequence[str], None] = '4f6f1d334794'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('festivals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('external_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('website', sa.String(length=200), nullable=True),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('logo_url', sa.String(length=255), nullable=True),
    sa.Column('founding_year', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_festivals_external_id'), 'festivals', ['external_id'], unique=True)
    op.create_table('festival_editions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('external_id', sa.String(length=80), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('edition_label', sa.String(length=50), nullable=True),
    sa.Column('dates', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('festival_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['festival_id'], ['festivals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_festival_editions_external_id'), 'festival_editions', ['external_id'], unique=True)
    op.create_table('festival_program_sections',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('edition_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['edition_id'], ['festival_editions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('festival_winner_categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('external_id', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('edition_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['edition_id'], ['festival_editions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_festival_winner_categories_external_id'), 'festival_winner_categories', ['external_id'], unique=True)
    op.create_table('festival_program_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('director', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('premiere', sa.String(length=50), nullable=True),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('movie_id', sa.Integer(), nullable=True),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['festival_program_sections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('festival_winners',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('movie_title', sa.String(length=200), nullable=True),
    sa.Column('movie_poster_url', sa.String(length=255), nullable=True),
    sa.Column('recipient', sa.String(length=100), nullable=True),
    sa.Column('director', sa.String(length=100), nullable=True),
    sa.Column('citation', sa.Text(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('movie_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['festival_winner_categories.id'], ),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('festival_winners')
    op.drop_table('festival_program_entries')
    op.drop_index(op.f('ix_festival_winner_categories_external_id'), table_name='festival_winner_categories')
    op.drop_table('festival_winner_categories')
    op.drop_table('festival_program_sections')
    op.drop_index(op.f('ix_festival_editions_external_id'), table_name='festival_editions')
    op.drop_table('festival_editions')
    op.drop_index(op.f('ix_festivals_external_id'), table_name='festivals')
    op.drop_table('festivals')
    # ### end Alembic commands ###
