"""add tmdb_id to movies table

Revision ID: 58c375e0c9ff
Revises: 6c92333a3e37
Create Date: 2025-11-02 07:30:07.789054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '58c375e0c9ff'
down_revision: Union[str, Sequence[str], None] = '6c92333a3e37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('tmdb_id', sa.Integer(), nullable=True))
    op.alter_column('movies', 'curation_status',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Status of movie curation: draft, pending_review, approved, rejected',
               existing_nullable=True)
    op.alter_column('movies', 'quality_score',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Quality score for the movie (0-100)',
               existing_nullable=True)
    op.alter_column('movies', 'curator_notes',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Notes from the curator about the movie',
               existing_nullable=True)
    op.alter_column('movies', 'curated_by_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='ID of the user who curated this movie',
               existing_nullable=True)
    op.alter_column('movies', 'curated_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Timestamp when the movie was curated',
               existing_nullable=True)
    op.alter_column('movies', 'last_reviewed_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Timestamp of the last review',
               existing_nullable=True)
    op.drop_index(op.f('ix_movies_curated_at'), table_name='movies')
    op.drop_index(op.f('ix_movies_curated_by_id'), table_name='movies')
    op.drop_index(op.f('ix_movies_curation_status'), table_name='movies')
    op.drop_index(op.f('ix_movies_quality_score'), table_name='movies')
    op.create_index(op.f('ix_movies_tmdb_id'), 'movies', ['tmdb_id'], unique=True)
    op.drop_constraint(op.f('fk_movies_curated_by_id'), 'movies', type_='foreignkey')
    op.create_foreign_key(None, 'movies', 'users', ['curated_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'movies', type_='foreignkey')
    op.create_foreign_key(op.f('fk_movies_curated_by_id'), 'movies', 'users', ['curated_by_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_movies_tmdb_id'), table_name='movies')
    op.create_index(op.f('ix_movies_quality_score'), 'movies', ['quality_score'], unique=False)
    op.create_index(op.f('ix_movies_curation_status'), 'movies', ['curation_status'], unique=False)
    op.create_index(op.f('ix_movies_curated_by_id'), 'movies', ['curated_by_id'], unique=False)
    op.create_index(op.f('ix_movies_curated_at'), 'movies', ['curated_at'], unique=False)
    op.alter_column('movies', 'last_reviewed_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='Timestamp of the last review',
               existing_nullable=True)
    op.alter_column('movies', 'curated_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='Timestamp when the movie was curated',
               existing_nullable=True)
    op.alter_column('movies', 'curated_by_id',
               existing_type=sa.INTEGER(),
               comment='ID of the user who curated this movie',
               existing_nullable=True)
    op.alter_column('movies', 'curator_notes',
               existing_type=sa.TEXT(),
               comment='Notes from the curator about the movie',
               existing_nullable=True)
    op.alter_column('movies', 'quality_score',
               existing_type=sa.INTEGER(),
               comment='Quality score for the movie (0-100)',
               existing_nullable=True)
    op.alter_column('movies', 'curation_status',
               existing_type=sa.VARCHAR(length=20),
               comment='Status of movie curation: draft, pending_review, approved, rejected',
               existing_nullable=True)
    op.drop_column('movies', 'tmdb_id')
    # ### end Alembic commands ###
