"""add awards domain

Revision ID: aa9093843641
Revises: 53572f1cd932
Create Date: 2025-10-18 13:43:29.434388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa9093843641'
down_revision: Union[str, Sequence[str], None] = '53572f1cd932'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('award_ceremonies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('external_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('short_name', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('logo_url', sa.String(length=255), nullable=True),
    sa.Column('background_image_url', sa.String(length=255), nullable=True),
    sa.Column('current_year', sa.Integer(), nullable=True),
    sa.Column('next_ceremony_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_award_ceremonies_external_id'), 'award_ceremonies', ['external_id'], unique=True)
    op.create_table('award_ceremony_years',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('external_id', sa.String(length=80), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('hosted_by', sa.Text(), nullable=True),
    sa.Column('background_image_url', sa.String(length=255), nullable=True),
    sa.Column('logo_url', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('highlights', sa.Text(), nullable=True),
    sa.Column('ceremony_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ceremony_id'], ['award_ceremonies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_award_ceremony_years_external_id'), 'award_ceremony_years', ['external_id'], unique=True)
    op.create_table('award_categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('external_id', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('ceremony_year_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ceremony_year_id'], ['award_ceremony_years.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_award_categories_external_id'), 'award_categories', ['external_id'], unique=True)
    op.create_table('award_nominations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('external_id', sa.String(length=80), nullable=False),
    sa.Column('nominee_type', sa.String(length=30), nullable=False),
    sa.Column('nominee_name', sa.String(length=200), nullable=False),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('entity_url', sa.String(length=255), nullable=True),
    sa.Column('details', sa.String(length=255), nullable=True),
    sa.Column('is_winner', sa.Boolean(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=True),
    sa.Column('person_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['award_categories.id'], ),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_award_nominations_external_id'), 'award_nominations', ['external_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_award_nominations_external_id'), table_name='award_nominations')
    op.drop_table('award_nominations')
    op.drop_index(op.f('ix_award_categories_external_id'), table_name='award_categories')
    op.drop_table('award_categories')
    op.drop_index(op.f('ix_award_ceremony_years_external_id'), table_name='award_ceremony_years')
    op.drop_table('award_ceremony_years')
    op.drop_index(op.f('ix_award_ceremonies_external_id'), table_name='award_ceremonies')
    op.drop_table('award_ceremonies')
    # ### end Alembic commands ###
