"""add visual treats domain

Revision ID: cc3e96904d6f
Revises: 348d9cc4848f
Create Date: 2025-10-18 14:46:00.952935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc3e96904d6f'
down_revision: Union[str, Sequence[str], None] = '348d9cc4848f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visual_treat_tag_lookup',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visual_treat_tag_lookup_name'), 'visual_treat_tag_lookup', ['name'], unique=True)
    op.create_table('visual_treats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('external_id', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=80), nullable=False),
    sa.Column('director', sa.String(length=100), nullable=True),
    sa.Column('cinematographer', sa.String(length=100), nullable=True),
    sa.Column('color_palette', sa.Text(), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=False),
    sa.Column('views', sa.Integer(), nullable=False),
    sa.Column('aspect_ratio', sa.String(length=20), nullable=True),
    sa.Column('resolution', sa.String(length=50), nullable=True),
    sa.Column('submitted_by', sa.String(length=100), nullable=True),
    sa.Column('movie_id', sa.Integer(), nullable=True),
    sa.Column('scene_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ),
    sa.ForeignKeyConstraint(['scene_id'], ['scenes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visual_treats_external_id'), 'visual_treats', ['external_id'], unique=True)
    op.create_table('visual_treat_tags',
    sa.Column('treat_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['visual_treat_tag_lookup.id'], ),
    sa.ForeignKeyConstraint(['treat_id'], ['visual_treats.id'], ),
    sa.PrimaryKeyConstraint('treat_id', 'tag_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('visual_treat_tags')
    op.drop_index(op.f('ix_visual_treats_external_id'), table_name='visual_treats')
    op.drop_table('visual_treats')
    op.drop_index(op.f('ix_visual_treat_tag_lookup_name'), table_name='visual_treat_tag_lookup')
    op.drop_table('visual_treat_tag_lookup')
    # ### end Alembic commands ###
