"""add pulse domain

Revision ID: d2ca5accbc79
Revises: cc3e96904d6f
Create Date: 2025-10-18 15:02:28.538260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2ca5accbc79'
down_revision: Union[str, Sequence[str], None] = 'cc3e96904d6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trending_topics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tag', sa.String(length=120), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=True),
    sa.Column('window_label', sa.String(length=10), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trending_topics_tag'), 'trending_topics', ['tag'], unique=False)
    op.create_table('pulses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('external_id', sa.String(length=80), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content_text', sa.Text(), nullable=False),
    sa.Column('content_media', sa.Text(), nullable=True),
    sa.Column('linked_type', sa.String(length=20), nullable=True),
    sa.Column('linked_external_id', sa.String(length=80), nullable=True),
    sa.Column('linked_title', sa.String(length=200), nullable=True),
    sa.Column('linked_poster_url', sa.String(length=255), nullable=True),
    sa.Column('linked_movie_id', sa.Integer(), nullable=True),
    sa.Column('hashtags', sa.Text(), nullable=True),
    sa.Column('reactions_json', sa.Text(), nullable=True),
    sa.Column('reactions_total', sa.Integer(), nullable=False),
    sa.Column('comments_count', sa.Integer(), nullable=False),
    sa.Column('shares_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('edited_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['linked_movie_id'], ['movies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pulses_created_at'), 'pulses', ['created_at'], unique=False)
    op.create_index(op.f('ix_pulses_external_id'), 'pulses', ['external_id'], unique=True)
    op.create_table('user_follows',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('follower_id', sa.Integer(), nullable=False),
    sa.Column('following_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['following_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_follows')
    op.drop_index(op.f('ix_pulses_external_id'), table_name='pulses')
    op.drop_index(op.f('ix_pulses_created_at'), table_name='pulses')
    op.drop_table('pulses')
    op.drop_index(op.f('ix_trending_topics_tag'), table_name='trending_topics')
    op.drop_table('trending_topics')
    # ### end Alembic commands ###
