"""add talent hub domain

Revision ID: f313c39a8c93
Revises: 123eb5dcd8f9
Create Date: 2025-10-18 16:02:41.408448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f313c39a8c93'
down_revision: Union[str, Sequence[str], None] = '123eb5dcd8f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('casting_calls',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('external_id', sa.String(length=80), nullable=False),
    sa.Column('project_title', sa.String(length=200), nullable=False),
    sa.Column('project_type', sa.String(length=30), nullable=False),
    sa.Column('production_company', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('production_start', sa.DateTime(), nullable=True),
    sa.Column('production_end', sa.DateTime(), nullable=True),
    sa.Column('location_city', sa.String(length=120), nullable=False),
    sa.Column('location_state', sa.String(length=120), nullable=True),
    sa.Column('location_country', sa.String(length=120), nullable=False),
    sa.Column('budget_range', sa.String(length=20), nullable=True),
    sa.Column('visibility', sa.String(length=20), nullable=False),
    sa.Column('submission_deadline', sa.DateTime(), nullable=False),
    sa.Column('posted_date', sa.DateTime(), nullable=False),
    sa.Column('poster_image', sa.String(length=255), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_casting_calls_external_id'), 'casting_calls', ['external_id'], unique=True)
    op.create_index(op.f('ix_casting_calls_location_country'), 'casting_calls', ['location_country'], unique=False)
    op.create_index(op.f('ix_casting_calls_posted_date'), 'casting_calls', ['posted_date'], unique=False)
    op.create_index(op.f('ix_casting_calls_project_type'), 'casting_calls', ['project_type'], unique=False)
    op.create_index(op.f('ix_casting_calls_status'), 'casting_calls', ['status'], unique=False)
    op.create_index(op.f('ix_casting_calls_visibility'), 'casting_calls', ['visibility'], unique=False)
    op.create_table('casting_call_roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('external_id', sa.String(length=80), nullable=False),
    sa.Column('call_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('department', sa.String(length=80), nullable=True),
    sa.Column('compensation', sa.String(length=20), nullable=False),
    sa.Column('payment_details', sa.Text(), nullable=True),
    sa.Column('requirements', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('audition_type', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['casting_calls.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_casting_call_roles_external_id'), 'casting_call_roles', ['external_id'], unique=True)
    op.create_index(op.f('ix_casting_call_roles_type'), 'casting_call_roles', ['type'], unique=False)
    op.create_table('submission_guidelines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('external_id', sa.String(length=80), nullable=False),
    sa.Column('call_id', sa.Integer(), nullable=False),
    sa.Column('required_materials', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('submission_method', sa.String(length=20), nullable=False),
    sa.Column('contact_email', sa.String(length=200), nullable=True),
    sa.Column('contact_website', sa.String(length=200), nullable=True),
    sa.Column('special_instructions', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['call_id'], ['casting_calls.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('call_id')
    )
    op.create_index(op.f('ix_submission_guidelines_external_id'), 'submission_guidelines', ['external_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_submission_guidelines_external_id'), table_name='submission_guidelines')
    op.drop_table('submission_guidelines')
    op.drop_index(op.f('ix_casting_call_roles_type'), table_name='casting_call_roles')
    op.drop_index(op.f('ix_casting_call_roles_external_id'), table_name='casting_call_roles')
    op.drop_table('casting_call_roles')
    op.drop_index(op.f('ix_casting_calls_visibility'), table_name='casting_calls')
    op.drop_index(op.f('ix_casting_calls_status'), table_name='casting_calls')
    op.drop_index(op.f('ix_casting_calls_project_type'), table_name='casting_calls')
    op.drop_index(op.f('ix_casting_calls_posted_date'), table_name='casting_calls')
    op.drop_index(op.f('ix_casting_calls_location_country'), table_name='casting_calls')
    op.drop_index(op.f('ix_casting_calls_external_id'), table_name='casting_calls')
    op.drop_table('casting_calls')
    # ### end Alembic commands ###
