import type { Review } from "./types"

export const mockReviews: Review[] = [
  {
    id: "review-1",
    title: "A Masterpiece of Dreams Within Dreams",
    content:
      "Christopher Nolan's 'Inception' is a mind-bending journey that challenges the very fabric of reality. The film's intricate plot, centered around dream infiltration, is executed with precision and intelligence. Leonardo DiCaprio delivers a powerful performance as Cobb, a man haunted by his past and desperate to return home. The supporting cast, including Joseph Gordon-Levitt and Elliot Page, provide depth to this complex narrative. Hans Zimmer's score is hauntingly beautiful, enhancing the film's emotional impact. The visual effects are groundbreaking, particularly the zero-gravity hallway scene which remains one of cinema's most impressive technical achievements. What elevates 'Inception' beyond a mere sci-fi thriller is its exploration of grief, guilt, and the power of ideas. The ambiguous ending continues to spark debate years later, proving the film's lasting impact on audiences. This is filmmaking at its finest - challenging, entertaining, and emotionally resonant.",
    rating: 9.5,
    date: "2023-12-15T14:30:00Z",
    hasSpoilers: false,
    isVerified: true,
    helpfulVotes: 342,
    unhelpfulVotes: 18,
    commentCount: 57,
    engagementScore: 85,
    author: {
      id: "user-1",
      name: "CinemaEnthusiast",
      avatarUrl: "/user-avatar-1.png",
    },
    movie: {
      id: "inception",
      title: "Inception",
      posterUrl: "/inception-movie-poster.png",
      year: 2010,
      genres: ["Science Fiction", "Action", "Thriller"],
      country: "United States",
      language: "English",
    },
  },
  {
    id: "review-2",
    title: "A Scathing Commentary on Class Divide",
    content:
      "Bong Joon-ho's 'Parasite' is a masterful blend of dark comedy, thriller, and social commentary. The film's examination of class inequality in South Korea resonates universally, making it accessible to audiences worldwide. The Kim family's infiltration of the wealthy Park household starts as a clever con but evolves into something far more complex and devastating. The performances are exceptional across the board, with Song Kang-ho particularly outstanding as the patriarch of the struggling Kim family. What makes 'Parasite' truly special is how it shifts tone seamlessly - from humorous to suspenseful to tragic - often within the same scene. The production design brilliantly contrasts the two worlds: the Parks' architectural marvel of a home versus the Kims' semi-basement dwelling. The film's shocking twists are earned through careful character development and thematic consistency. Its Best Picture Oscar win was well-deserved, breaking barriers for international cinema. This is a film that demands multiple viewings to fully appreciate its layered storytelling and visual symbolism.",
    rating: 9.8,
    date: "2023-11-20T09:15:00Z",
    hasSpoilers: true,
    isVerified: true,
    helpfulVotes: 289,
    unhelpfulVotes: 12,
    commentCount: 43,
    engagementScore: 92,
    mediaUrls: ["/parasite-movie-poster.png"],
    author: {
      id: "user-2",
      name: "FilmCritic101",
      avatarUrl: "/user-avatar-2.png",
    },
    movie: {
      id: "parasite",
      title: "Parasite",
      posterUrl: "/parasite-movie-poster.png",
      year: 2019,
      genres: ["Thriller", "Comedy", "Drama"],
      country: "South Korea",
      language: "Korean",
    },
  },
  {
    id: "review-3",
    title: "The Definitive Superhero Film",
    content:
      "The Dark Knight transcends the superhero genre to become one of the greatest crime thrillers ever made. Christopher Nolan's vision of Gotham City feels grounded and real, making the stakes genuinely impactful. Heath Ledger's performance as the Joker is nothing short of legendary - a chaotic force of nature that challenges not just Batman's physical abilities but his moral code. Christian Bale perfectly embodies the duality of Bruce Wayne/Batman, while Aaron Eckhart's transformation from Gotham's 'white knight' to the vengeful Two-Face is tragic and compelling. The film's exploration of themes like chaos versus order, surveillance ethics, and the limits of heroism elevates it beyond typical comic book fare. Hans Zimmer and James Newton Howard's score creates a constant sense of tension and urgency. The IMAX sequences, particularly the opening bank heist, showcase Nolan's technical mastery. This film redefined what superhero movies could be and its influence can be seen in countless films that followed. It remains the gold standard of the genre.",
    rating: 9.7,
    date: "2023-10-05T16:45:00Z",
    hasSpoilers: false,
    isVerified: true,
    helpfulVotes: 412,
    unhelpfulVotes: 24,
    commentCount: 78,
    engagementScore: 95,
    author: {
      id: "user-3",
      name: "ComicBookGuru",
      avatarUrl: "/user-avatar-3.png",
    },
    movie: {
      id: "the-dark-knight",
      title: "The Dark Knight",
      posterUrl: "/dark-knight-poster.png",
      year: 2008,
      genres: ["Action", "Crime", "Drama", "Thriller"],
      country: "United States",
      language: "English",
    },
  },
  {
    id: "review-4",
    title: "Tarantino's Masterpiece of Nonlinear Storytelling",
    content:
      "Pulp Fiction remains Quentin Tarantino's defining work - a bold, innovative film that forever changed cinema. The nonlinear narrative structure was revolutionary at the time and still feels fresh today. The dialogue is endlessly quotable, balancing humor, tension, and philosophical musings with remarkable ease. John Travolta's career revival as Vincent Vega, Samuel L. Jackson's iconic Jules Winnfield, and Uma Thurman's enigmatic Mia Wallace are performances for the ages. The film's eclectic soundtrack perfectly complements its unique tone, becoming inseparable from the viewing experience. What's most impressive is how Tarantino weaves seemingly disparate stories into a cohesive whole, with themes of redemption, fate, and moral ambiguity connecting throughout. The infamous 'briefcase' with its mysterious golden glow exemplifies Tarantino's genius - creating endless discussion without explicit explanation. From the Jack Rabbit Slim's twist contest to the adrenaline shot sequence, the film delivers unforgettable moments that have been referenced and parodied countless times. Pulp Fiction didn't just influence independent cinema; it redefined it.",
    rating: 9.6,
    date: "2023-09-12T11:20:00Z",
    hasSpoilers: false,
    isVerified: false,
    helpfulVotes: 356,
    unhelpfulVotes: 31,
    commentCount: 62,
    engagementScore: 88,
    author: {
      id: "user-4",
      name: "MovieBuffExtraordinaire",
      avatarUrl: "/user-avatar-4.png",
    },
    movie: {
      id: "pulp-fiction",
      title: "Pulp Fiction",
      posterUrl: "/pulp-fiction-poster.png",
      year: 1994,
      genres: ["Crime", "Drama"],
      country: "United States",
      language: "English",
    },
  },
  {
    id: "review-5",
    title: "A Brilliant Exploration of Masculinity and Consumerism",
    content:
      "Fight Club is that rare film that becomes more relevant with each passing year. David Fincher's stylish direction brings Chuck Palahniuk's novel to life with visceral energy and dark humor. Edward Norton and Brad Pitt deliver career-defining performances as the unnamed narrator and Tyler Durden - two sides of a fractured psyche. The film's critique of consumerism and masculine identity crisis resonates even more strongly in today's brand-obsessed, identity-focused culture. The twist ending, which I won't spoil here, completely transforms the viewing experience on rewatch, revealing carefully planted clues throughout. The Dust Brothers' electronic score creates a perfect atmosphere of urban alienation and barely contained chaos. Fincher's visual techniques - the subliminal flashes, the apartment catalog sequence, the distinctive color palette - all contribute to the film's unique aesthetic. While initially polarizing upon release, Fight Club has rightfully earned its place as one of the most influential films of its era. It's a testament to the film's power that its ideas and imagery have permeated popular culture so thoroughly.",
    rating: 9.4,
    date: "2023-08-28T15:10:00Z",
    hasSpoilers: true,
    isVerified: true,
    helpfulVotes: 298,
    unhelpfulVotes: 27,
    commentCount: 51,
    engagementScore: 82,
    mediaUrls: ["/fight-club-poster.png"],
    author: {
      id: "user-5",
      name: "CinephileSupreme",
      avatarUrl: "/user-avatar-5.png",
    },
    movie: {
      id: "fight-club",
      title: "Fight Club",
      posterUrl: "/fight-club-poster.png",
      year: 1999,
      genres: ["Drama"],
      country: "United States",
      language: "English",
    },
  },
  {
    id: "review-6",
    title: "Revolutionary Sci-Fi That Defined a Generation",
    content:
      "The Matrix is more than just a groundbreaking sci-fi film; it's a cultural phenomenon that changed how we view reality and technology. The Wachowskis created a perfect blend of philosophical concepts, revolutionary visual effects, and exhilarating action sequences. Keanu Reeves embodies Neo's transformation from confused programmer to messianic figure with a perfect balance of vulnerability and growing confidence. The 'bullet time' effect may be the most imitated visual technique in modern cinema, but it's the film's exploration of simulation theory and control systems that gives it lasting intellectual weight. The production design creates two distinct worlds - the green-tinted Matrix and the gritty 'real world' of the Nebuchadnezzar - with meticulous attention to detail. The fight choreography, influenced by Hong Kong cinema and wire-fu techniques, raised the bar for action sequences in Western films. The film's influence extends beyond cinema into fashion, video games, and even political discourse (the 'red pill' concept). While its sequels may have divided audiences, the original Matrix remains a perfect fusion of style and substance that continues to resonate with new generations of viewers.",
    rating: 9.3,
    date: "2023-07-19T10:05:00Z",
    hasSpoilers: false,
    isVerified: true,
    helpfulVotes: 325,
    unhelpfulVotes: 22,
    commentCount: 59,
    engagementScore: 86,
    author: {
      id: "user-6",
      name: "SciFiEnthusiast",
      avatarUrl: "/user-avatar-6.png",
    },
    movie: {
      id: "the-matrix",
      title: "The Matrix",
      posterUrl: "/matrix-poster.png",
      year: 1999,
      genres: ["Action", "Science Fiction"],
      country: "United States",
      language: "English",
    },
  },
  {
    id: "review-7",
    title: "A Cosmic Journey Through Love and Science",
    content:
      "Interstellar is Christopher Nolan's most ambitious and emotional film, blending hard science fiction with profound human drama. The film's visualization of complex astrophysical concepts - wormholes, black holes, time dilation - is scientifically grounded yet visually spectacular. Matthew McConaughey delivers a powerfully emotional performance as Cooper, a father forced to choose between saving humanity and returning to his children. The scene where he watches years of accumulated messages from his children is devastating in its emotional impact. Hans Zimmer's organ-driven score is transcendent, particularly during the docking sequence - one of cinema's most intense moments. The film's exploration of love as a force that transcends dimensions might seem sentimental in another context, but Nolan earns this theme through rigorous storytelling. The production design seamlessly blends practical effects with CGI to create believable alien worlds and space environments. While some critics found fault with the film's third act, I believe it's a perfect culmination of the scientific and emotional threads. Interstellar asks big questions about humanity's place in the cosmos and our responsibility to future generations, making it not just spectacular entertainment but thought-provoking art.",
    rating: 9.2,
    date: "2023-06-30T13:25:00Z",
    hasSpoilers: true,
    isVerified: false,
    helpfulVotes: 276,
    unhelpfulVotes: 35,
    commentCount: 48,
    engagementScore: 79,
    mediaUrls: ["/interstellar-poster.png"],
    author: {
      id: "user-7",
      name: "SpaceExplorer",
      avatarUrl: "/user-avatar-7.png",
    },
    movie: {
      id: "interstellar",
      title: "Interstellar",
      posterUrl: "/interstellar-poster.png",
      year: 2014,
      genres: ["Adventure", "Drama", "Science Fiction"],
      country: "United States",
      language: "English",
    },
  },
  {
    id: "review-8",
    title: "The Ultimate Tale of Hope and Redemption",
    content:
      "The Shawshank Redemption is storytelling perfection - a film that finds beauty and hope in the darkest of circumstances. Frank Darabont's adaptation of Stephen King's novella is a masterclass in pacing, character development, and emotional resonance. Tim Robbins' Andy Dufresne and Morgan Freeman's Red form one of cinema's most memorable friendships, their contrasting personalities - hope versus resignation - creating the film's emotional core. The film's examination of institutionalization and the struggle to maintain dignity in a dehumanizing system remains powerfully relevant. Roger Deakins' cinematography transforms Shawshank Prison into a character itself, with lighting that evolves subtly as the decades pass. Thomas Newman's score is delicate and evocative, never manipulating emotions but enhancing them naturally. The film's structure, spanning decades, allows for a satisfying character arc that feels earned rather than contrived. While it famously underperformed at the box office, its discovery on home video and cable television transformed it into a beloved classic. The film's final act, with Andy's escape and Red's journey to Zihuatanejo, delivers one of the most satisfying conclusions in film history. The Shawshank Redemption reminds us that hope is indeed a good thing, maybe the best of things.",
    rating: 9.7,
    date: "2023-05-22T17:40:00Z",
    hasSpoilers: false,
    isVerified: true,
    helpfulVotes: 389,
    unhelpfulVotes: 14,
    commentCount: 72,
    engagementScore: 94,
    author: {
      id: "user-8",
      name: "ClassicFilmLover",
      avatarUrl: "/user-avatar-8.png",
    },
    movie: {
      id: "the-shawshank-redemption",
      title: "The Shawshank Redemption",
      posterUrl: "/shawshank-redemption-poster.png",
      year: 1994,
      genres: ["Drama"],
      country: "United States",
      language: "English",
    },
  },
  {
    id: "review-9",
    title: "The Definitive Gangster Epic",
    content:
      "The Godfather remains the gold standard for crime dramas - a perfect film in every aspect. Francis Ford Coppola's direction is flawless, creating a rich, immersive world of family, honor, and power. Marlon Brando's Don Vito Corleone is one of cinema's most iconic characters, with every mannerism and mumbled line becoming part of our cultural lexicon. Al Pacino's transformation from reluctant outsider to ruthless don is a masterclass in subtle character development. Gordon Willis's cinematography, with its amber hues and shadow-filled compositions, creates a visual language that has defined our image of the mafia. Nino Rota's haunting score instantly evokes the film's themes of tradition and tragedy. The screenplay balances intimate family drama with the broader scope of organized crime in post-war America. The film's set pieces - the opening wedding sequence, the horse head, the restaurant shooting, the baptism montage - are studied in film schools for their perfect execution. Beyond its technical excellence, The Godfather resonates because it's ultimately about family and the American dream corrupted. It's a film that improves with each viewing, revealing new layers of meaning and artistry. Simply put, it's an offer no film lover can refuse.",
    rating: 10.0,
    date: "2023-04-15T12:30:00Z",
    hasSpoilers: false,
    isVerified: true,
    helpfulVotes: 421,
    unhelpfulVotes: 9,
    commentCount: 83,
    engagementScore: 98,
    author: {
      id: "user-9",
      name: "FilmHistorian",
      avatarUrl: "/user-avatar-9.png",
    },
    movie: {
      id: "the-godfather",
      title: "The Godfather",
      posterUrl: "/classic-mob-poster.png",
      year: 1972,
      genres: ["Crime", "Drama"],
      country: "United States",
      language: "English",
    },
  },
  {
    id: "review-10",
    title: "A Visceral Portrait of Urban Poverty and Crime",
    content:
      "City of God is a kinetic, unflinching look at life in Rio de Janeiro's favelas that hits with the force of a sledgehammer. Fernando Meirelles and Kátia Lund's direction brings a documentary-like authenticity to this fictional story, using non-professional actors from actual favelas to create unparalleled realism. The film's structure, following multiple characters across different time periods, creates a rich tapestry of interconnected lives affected by systemic poverty and violence. The cinematography employs a distinctive visual style for each era - the golden-hued 60s contrasting with the harsh, desaturated look of the 70s and 80s as violence escalates. The performances, particularly by Alexandre Rodrigues as Rocket and Leandro Firmino as Li'l Zé, are astonishingly natural and compelling. The film's energy comes from its innovative editing techniques, rapid-fire cutting, and dynamic camera movements that mirror the chaotic environment. While unflinching in its depiction of violence, the film never feels exploitative - it's a necessary window into a reality often ignored. City of God transcends its crime genre trappings to become a powerful social document about how environment shapes destiny. It's a film that leaves you breathless and haunted, with images and characters that remain seared in memory long after viewing.",
    rating: 9.5,
    date: "2023-03-08T09:50:00Z",
    hasSpoilers: false,
    isVerified: false,
    helpfulVotes: 312,
    unhelpfulVotes: 19,
    commentCount: 54,
    engagementScore: 87,
    mediaUrls: ["/city-of-god-poster.png"],
    author: {
      id: "user-10",
      name: "WorldCinemaBuff",
      avatarUrl: "/user-avatar-1.png",
    },
    movie: {
      id: "city-of-god",
      title: "City of God",
      posterUrl: "/city-of-god-poster.png",
      year: 2002,
      genres: ["Crime", "Drama"],
      country: "Brazil",
      language: "Portuguese",
    },
  },
  {
    id: "review-11",
    title: "A Mesmerizing Exploration of Unrequited Love",
    content:
      "In the Mood for Love is cinema as pure visual poetry - a film that communicates as much through glances, gestures, and atmosphere as through dialogue. Wong Kar-wai's direction creates a dreamlike mood that perfectly captures the ache of forbidden attraction. Tony Leung and Maggie Cheung deliver performances of remarkable subtlety, conveying complex emotions with minimal expression. Their characters' restraint makes the unexpressed passion all the more powerful. Christopher Doyle's cinematography is simply breathtaking - the saturated colors, the play of light and shadow, the framing through doorways and windows all emphasize the characters' emotional isolation. The recurring waltz theme by Shigeru Umebayashi has become inseparable from the film's images, creating one of cinema's most perfect marriages of music and visuals. The film's 1960s Hong Kong setting is rendered with meticulous attention to period detail, from the cheongsam dresses to the cramped apartment buildings. What makes In the Mood for Love truly special is its restraint - what isn't shown or said carries as much weight as what is. The final scene at Angkor Wat, with its whispered secret, is one of cinema's most poignant conclusions. This is a film that doesn't just tell a story of unrequited love; it makes you feel it in your bones.",
    rating: 9.6,
    date: "2023-02-14T16:15:00Z",
    hasSpoilers: false,
    isVerified: true,
    helpfulVotes: 287,
    unhelpfulVotes: 16,
    commentCount: 47,
    engagementScore: 84,
    author: {
      id: "user-11",
      name: "ArtCinemaAficionado",
      avatarUrl: "/user-avatar-2.png",
    },
    movie: {
      id: "in-the-mood-for-love",
      title: "In the Mood for Love",
      posterUrl: "/in-the-mood-for-love-poster.png",
      year: 2000,
      genres: ["Drama", "Romance"],
      country: "Hong Kong",
      language: "Cantonese",
    },
  },
  {
    id: "review-12",
    title: "A Devastating Masterpiece of Animated Storytelling",
    content:
      "Grave of the Fireflies is perhaps the most powerful anti-war film ever made, animated or otherwise. Isao Takahata's unflinching portrayal of two orphaned siblings struggling to survive in the final days of World War II is both beautiful and unbearably tragic. The film's power comes from its simplicity and restraint - there are no villains, just the terrible consequences of war on innocent lives. The animation, while less fantastical than other Studio Ghibli works, captures the beauty of everyday moments amidst devastation - fireflies illuminating the darkness, a simple meal shared between siblings. The relationship between teenage Seita and his young sister Setsuko is rendered with heartbreaking authenticity. The film's structure, beginning with Seita's death and then flashing back, removes any false hope and forces us to witness the inevitable tragedy. What makes Grave of the Fireflies particularly devastating is how it shows the failure of society - the indifference and selfishness that emerge in times of crisis. This isn't just a great animated film; it's one of cinema's most powerful humanist statements. It should be required viewing for anyone who needs to understand the true cost of war on civilian populations. Be warned: this film will break your heart, but it's a necessary experience.",
    rating: 9.8,
    date: "2023-01-20T11:05:00Z",
    hasSpoilers: true,
    isVerified: true,
    helpfulVotes: 356,
    unhelpfulVotes: 11,
    commentCount: 64,
    engagementScore: 93,
    author: {
      id: "user-12",
      name: "AnimationScholar",
      avatarUrl: "/user-avatar-3.png",
    },
    movie: {
      id: "grave-of-the-fireflies",
      title: "Grave of the Fireflies",
      posterUrl: "/grave-of-the-fireflies-poster.png",
      year: 1988,
      genres: ["Animation", "Drama", "War"],
      country: "Japan",
      language: "Japanese",
    },
  },
  {
    id: "review-13",
    title: "The Poetic Beginning of the Apu Trilogy",
    content:
      "Pather Panchali is a miracle of a film - made on a shoestring budget by a first-time director, yet achieving a level of humanism and poetic realism that remains unmatched. Satyajit Ray's camera captures rural Bengali life with an authenticity that feels documentary-like while maintaining a lyrical beauty. The film follows young Apu and his family through daily struggles, small joys, and devastating tragedies with unflinching honesty and deep compassion. The non-professional cast delivers performances of remarkable naturalism, particularly Chunibala Devi as the elderly aunt Indir. Ravi Shankar's sitar score perfectly complements the visual poetry, becoming one of cinema's most effective musical accompaniments. What's most impressive is Ray's patience - he allows scenes to unfold at their natural rhythm, finding profound meaning in seemingly mundane moments. The famous sequence of the children running through a field of swaying kash flowers to see a train remains one of cinema's most joyous expressions of childhood wonder. The film's depiction of poverty never feels exploitative or sentimental - it's simply the reality these characters inhabit, portrayed with dignity. Pather Panchali revolutionized Indian cinema and announced Ray as a major international filmmaker. Its influence can be seen in everything from Italian Neorealism to contemporary social realist cinema. This is essential viewing for anyone who cares about film as art.",
    rating: 9.4,
    date: "2022-12-05T14:20:00Z",
    hasSpoilers: false,
    isVerified: false,
    helpfulVotes: 245,
    unhelpfulVotes: 22,
    commentCount: 41,
    engagementScore: 80,
    author: {
      id: "user-13",
      name: "WorldCinemaExpert",
      avatarUrl: "/user-avatar-4.png",
    },
    movie: {
      id: "pather-panchali",
      title: "Pather Panchali",
      posterUrl: "/pather-panchali-poster.png",
      year: 1955,
      genres: ["Drama"],
      country: "India",
      language: "Bengali",
    },
  },
  {
    id: "review-14",
    title: "Bergman's Existential Masterpiece",
    content:
      "The Seventh Seal is cinema at its most philosophically profound - a medieval allegory that grapples with humanity's eternal questions about faith, death, and meaning. Ingmar Bergman creates unforgettable imagery that has become iconic: the knight playing chess with Death on a desolate beach, the silhouetted dance of death against the twilight sky. Max von Sydow's performance as the knight Antonius Block captures the perfect balance of intellectual doubt and spiritual yearning. The film's setting during the Black Death provides the perfect backdrop for its existential themes, with the specter of mortality ever-present. What prevents the film from becoming merely a philosophical treatise is Bergman's deep humanism and moments of unexpected warmth and humor. The family of traveling performers - particularly Jof, Mia, and their infant son - represent a life-affirming counterpoint to the knight's spiritual crisis. Gunnar Fischer's stark black-and-white cinematography creates a visual language that feels both historically authentic and dreamlike. While dealing with weighty themes, The Seventh Seal remains remarkably accessible - its questions about God's silence and the search for meaning resonate regardless of one's religious beliefs. This is a film that has lost none of its power to provoke thought and stir the soul, remaining as vital today as when it was made in 1957.",
    rating: 9.5,
    date: "2022-11-18T10:35:00Z",
    hasSpoilers: false,
    isVerified: true,
    helpfulVotes: 278,
    unhelpfulVotes: 19,
    commentCount: 52,
    engagementScore: 83,
    mediaUrls: ["/seventh-seal-poster.png"],
    author: {
      id: "user-14",
      name: "PhilosophicalCinephile",
      avatarUrl: "/user-avatar-5.png",
    },
    movie: {
      id: "the-seventh-seal",
      title: "The Seventh Seal",
      posterUrl: "/seventh-seal-poster.png",
      year: 1957,
      genres: ["Drama", "Fantasy"],
      country: "Sweden",
      language: "Swedish",
    },
  },
  {
    id: "review-15",
    title: "A Monumental Achievement in Historical Filmmaking",
    content:
      "Oppenheimer is Christopher Nolan's most mature and accomplished film - a towering achievement that manages to be both intellectually rigorous and emotionally devastating. Cillian Murphy delivers the performance of his career as J. Robert Oppenheimer, capturing both the brilliant physicist and the deeply flawed man with nuanced precision. The film's structure, alternating between color sequences from Oppenheimer's perspective and black-and-white scenes from the security hearing that would later destroy his reputation, creates a complex portrait of both the man and the era. The Trinity test sequence is one of the most awe-inspiring and terrifying moments in recent cinema, conveying both the scientific achievement and the moral horror of the atomic bomb's creation. The supporting cast is extraordinary, particularly Robert Downey Jr. as Lewis Strauss, whose petty vendetta against Oppenheimer drives the film's parallel narrative. Ludwig Göransson's score perfectly complements the mounting tension, particularly in the film's final hour. What elevates Oppenheimer beyond a standard biopic is how it uses one man's story to explore larger themes about scientific responsibility, government power, and the moral compromises of wartime. The film's three-hour runtime feels justified, allowing Nolan to fully explore the complexity of his subject. This is historical filmmaking of the highest order - meticulously researched yet dramatically compelling, intellectually challenging yet emotionally resonant.",
    rating: 9.7,
    date: "2023-07-25T15:55:00Z",
    hasSpoilers: false,
    isVerified: true,
    helpfulVotes: 367,
    unhelpfulVotes: 28,
    commentCount: 71,
    engagementScore: 91,
    author: {
      id: "user-15",
      name: "HistoricalFilmBuff",
      avatarUrl: "/user-avatar-6.png",
    },
    movie: {
      id: "oppenheimer",
      title: "Oppenheimer",
      posterUrl: "/oppenheimer-inspired-poster.png",
      year: 2023,
      genres: ["Biography", "Drama", "History"],
      country: "United States",
      language: "English",
    },
  },
  {
    id: "review-16",
    title: "A Vibrant, Feminist Reimagining",
    content:
      "Barbie is a surprisingly subversive and intelligent film disguised as a candy-colored comedy. Greta Gerwig has accomplished something remarkable - creating a film that works as both a critique and celebration of the iconic doll's complicated legacy. Margot Robbie is perfectly cast as the titular Barbie, bringing depth and nuance to what could have been a one-dimensional role. Ryan Gosling steals every scene as Ken, hilariously embodying toxic masculinity while remaining sympathetic. The production design is a triumph, creating a Barbie world that feels both artificial (as it should) and tangible. The film's journey from the perfect Barbie Land to the messiness of the real world provides a clever framework for exploring gender roles and societal expectations. What surprised me most was the film's emotional depth, particularly in Barbie's interactions with real-world women and her growing understanding of what it means to be human. The screenplay balances meta-humor, social commentary, and genuine heart with remarkable dexterity. The musical numbers are delightful, particularly Ken's beach-rock anthem about the patriarchy. While some might dismiss Barbie as merely a corporate product, Gerwig has used this platform to create something genuinely subversive and thought-provoking. It's a film that manages to entertain children while giving adults plenty to discuss afterward - a rare achievement in mainstream cinema.",
    rating: 8.8,
    date: "2023-07-28T13:10:00Z",
    hasSpoilers: false,
    isVerified: false,
    helpfulVotes: 289,
    unhelpfulVotes: 42,
    commentCount: 63,
    engagementScore: 85,
    mediaUrls: ["/barbie-movie-poster.png"],
    author: {
      id: "user-16",
      name: "PopCultureAnalyst",
      avatarUrl: "/user-avatar-7.png",
    },
    movie: {
      id: "barbie",
      title: "Barbie",
      posterUrl: "/barbie-movie-poster.png",
      year: 2023,
      genres: ["Adventure", "Comedy", "Fantasy"],
      country: "United States",
      language: "English",
    },
  },
  {
    id: "review-17",
    title: "A Mesmerizing Sci-Fi Epic That Honors Its Source",
    content:
      "Dune: Part Two builds upon the foundation of its predecessor to deliver a truly epic science fiction experience. Denis Villeneuve continues to prove he's one of our finest filmmakers, bringing Frank Herbert's complex novel to life with stunning visuals and emotional depth. Timothée Chalamet fully embodies Paul Atreides' transformation from displaced noble to messianic figure, conveying both his growing power and his horror at what he's becoming. The expansion of Zendaya's role as Chani provides the emotional core of the film, her relationship with Paul adding necessary humanity to the grand political machinations. The action sequences are breathtaking, particularly the sandworm riding scenes which are among the most exhilarating moments in recent cinema. Hans Zimmer's score remains otherworldly and powerful, enhancing the alien nature of Arrakis. The film's exploration of colonialism, religious manipulation, and environmental exploitation gives it intellectual weight beyond its spectacular visuals. The supporting cast is uniformly excellent, with standout performances from Rebecca Ferguson, Javier Bardem, and Austin Butler as the terrifying Feyd-Rautha. What impresses most is how Villeneuve balances the intimate and the epic - personal moments of character development are given as much importance as massive battle sequences. This is science fiction filmmaking at its finest, respecting both its source material and its audience's intelligence.",
    rating: 9.6,
    date: "2024-03-05T16:40:00Z",
    hasSpoilers: true,
    isVerified: true,
    helpfulVotes: 312,
    unhelpfulVotes: 18,
    commentCount: 57,
    engagementScore: 90,
    author: {
      id: "user-17",
      name: "SciFiConnoisseur",
      avatarUrl: "/user-avatar-8.png",
    },
    movie: {
      id: "dune-part-two",
      title: "Dune: Part Two",
      posterUrl: "/dune-part-two-poster.png",
      year: 2024,
      genres: ["Action", "Adventure", "Drama", "Science Fiction"],
      country: "United States",
      language: "English",
    },
  },
  {
    id: "review-18",
    title: "A Bizarre, Beautiful Feminist Fairy Tale",
    content:
      "Poor Things is Yorgos Lanthimos at his most ambitious and visually stunning - a Victorian sci-fi feminist fable that defies easy categorization. Emma Stone delivers a career-best performance as Bella Baxter, a woman with the brain of an infant who rapidly evolves into a fiercely independent being. Her physical performance is remarkable, charting Bella's development from jerky, childlike movements to confident adulthood. The film's production design creates a surreal steampunk version of Victorian Europe that feels both familiar and alien. Willem Dafoe brings pathos to Dr. Godwin Baxter, the Frankenstein-like figure whose own trauma informs his creation of Bella. Mark Ruffalo is delightfully unhinged as the libertine Duncan Wedderburn, subverting his usual nice-guy persona. What makes Poor Things so refreshing is its sex-positive approach to female autonomy - Bella's sexual awakening is portrayed without judgment or exploitation. The film's black humor prevents the weighty themes from becoming ponderous, with many laugh-out-loud moments amidst the philosophical musings. Robbie Ryan's cinematography, shifting from black-and-white to increasingly saturated color as Bella's world expands, is simply gorgeous. While some viewers might be put off by the film's explicit content and bizarre imagery, those willing to embrace its strangeness will be rewarded with one of the most original and thought-provoking films in recent memory. Poor Things is a true original - weird, wonderful, and utterly unforgettable.",
    rating: 9.2,
    date: "2024-01-12T11:25:00Z",
    hasSpoilers: false,
    isVerified: true,
    helpfulVotes: 276,
    unhelpfulVotes: 31,
    commentCount: 49,
    engagementScore: 82,
    author: {
      id: "user-18",
      name: "ArtFilmEnthusiast",
      avatarUrl: "/user-avatar-9.png",
    },
    movie: {
      id: "poor-things",
      title: "Poor Things",
      posterUrl: "/poor-things-poster.png",
      year: 2023,
      genres: ["Comedy", "Drama", "Romance", "Science Fiction"],
      country: "United Kingdom",
      language: "English",
    },
  },
  {
    id: "review-19",
    title: "Scorsese's Haunting Examination of American Greed",
    content:
      "Killers of the Flower Moon is Martin Scorsese at his most contemplative and damning - a methodical, devastating examination of America's exploitation of Native Americans. The decision to tell this story primarily through the perspective of the white perpetrators rather than the Osage victims is controversial but effective, forcing viewers to confront uncomfortable truths about American history. Leonardo DiCaprio gives a complex performance as Ernest Burkhart, a weak-willed man torn between loyalty to his manipulative uncle and love for his Osage wife. Robert De Niro is chillingly effective as William Hale, presenting a public face of friendship to the Osage while orchestrating their murders. The true revelation is Lily Gladstone as Mollie Burkhart, whose quiet dignity and suffering provide the film's moral center. Scorsese's direction is patient and deliberate, allowing the horror to build gradually rather than relying on sensationalism. Rodrigo Prieto's cinematography captures both the beauty of the Oklahoma landscape and the darkness lurking beneath the surface. The film's 3.5-hour runtime is justified, allowing for a thorough exploration of this complex historical episode. The final act, which breaks the fourth wall to acknowledge the limitations of this storytelling approach, is a bold choice that forces viewers to consider how Native American stories have been historically marginalized. This is not just a great film but an important one - a reckoning with a shameful chapter of American history that resonates with ongoing issues of exploitation and justice.",
    rating: 9.4,
    date: "2023-10-30T14:15:00Z",
    hasSpoilers: false,
    isVerified: true,
    helpfulVotes: 298,
    unhelpfulVotes: 25,
    commentCount: 54,
    engagementScore: 87,
    mediaUrls: ["/killers-of-the-flower-moon-poster.png"],
    author: {
      id: "user-19",
      name: "FilmHistoryProfessor",
      avatarUrl: "/user-avatar-1.png",
    },
    movie: {
      id: "killers-of-the-flower-moon",
      title: "Killers of the Flower Moon",
      posterUrl: "/killers-of-the-flower-moon-poster.png",
      year: 2023,
      genres: ["Crime", "Drama", "History"],
      country: "United States",
      language: "English",
    },
  },
  {
    id: "review-20",
    title: "A Thoughtful, Visually Stunning Sci-Fi Gem",
    content:
      "The Creator is that rare modern sci-fi film that prioritizes ideas and emotion over spectacle, though its visual achievements are considerable. Gareth Edwards has crafted a film that feels both epic in scope and intimate in character, exploring the relationship between humans and AI with nuance rather than simplistic good/evil binaries. John David Washington delivers a soulful performance as Joshua, a soldier whose personal loss complicates his mission to destroy an AI weapon. The real standout is newcomer Madeleine Yuna Voyles as Alphie, the AI child who forms the emotional center of the film. The world-building is exceptional, creating a near-future that feels lived-in and plausible, with AI integration varying across different regions and cultures. What's most impressive is how Edwards achieved such stunning visuals on a relatively modest budget (for sci-fi), using practical locations in Southeast Asia enhanced with seamless visual effects. The film's exploration of themes like personhood, the ethics of creation, and the cycle of fear and violence gives it a depth often lacking in the genre. Hans Zimmer's score beautifully complements the emotional journey without overwhelming it. While some plot elements feel familiar from other sci-fi works, The Creator combines them in ways that feel fresh and thoughtful. In an era of franchise filmmaking, this original sci-fi story stands out as a reminder of what the genre can achieve at its best - using speculative concepts to explore deeply human questions.",
    rating: 8.7,
    date: "2023-10-02T09:45:00Z",
    hasSpoilers: false,
    isVerified: false,
    helpfulVotes: 254,
    unhelpfulVotes: 29,
    commentCount: 46,
    engagementScore: 78,
    author: {
      id: "user-20",
      name: "TechAndFilmBuff",
      avatarUrl: "/user-avatar-2.png",
    },
    movie: {
      id: "the-creator",
      title: "The Creator",
      posterUrl: "/the-creator-poster.png",
      year: 2023,
      genres: ["Action", "Adventure", "Drama", "Science Fiction"],
      country: "United States",
      language: "English",
    },
  },
]
