import type { Scene } from "./types"

export const mockScenes: Scene[] = [
  {
    id: "scene-001",
    title: "Dream Collapse",
    description:
      "The iconic scene where the dream world begins to fold and collapse upon itself, showcasing groundbreaking visual effects and symbolism.",
    thumbnail: "/placeholder.svg?height=720&width=1280&query=city%20folding%20inception%20scene",
    duration: "2:45",
    movieId: "inception",
    movieTitle: "Inception",
    moviePoster: "/inception-movie-poster.png",
    releaseYear: 2010,
    director: "Christopher Nolan",
    cinematographer: "Wally Pfister",
    genres: ["sci-fi", "action", "thriller"],
    sceneType: "vfx",
    viewCount: 24853,
    commentCount: 342,
    isPopular: true,
    isVisualTreat: true,
    addedDate: "2023-01-15T14:30:00Z",
  },
  {
    id: "scene-002",
    title: "Hallway Fight",
    description:
      "A gravity-defying fight sequence in a rotating hotel hallway that demonstrates innovative practical effects and choreography.",
    thumbnail: "/placeholder.svg?height=720&width=1280&query=rotating%20hallway%20fight%20scene",
    duration: "3:20",
    movieId: "inception",
    movieTitle: "Inception",
    moviePoster: "/inception-movie-poster.png",
    releaseYear: 2010,
    director: "Christopher Nolan",
    cinematographer: "Wally Pfister",
    genres: ["sci-fi", "action", "thriller"],
    sceneType: "action",
    viewCount: 18742,
    commentCount: 256,
    isPopular: true,
    isVisualTreat: true,
    addedDate: "2023-02-10T09:15:00Z",
  },
  {
    id: "scene-003",
    title: "Basement Flood",
    description:
      "The tense scene where the wealthy family's home is flooded during a storm, revealing class tensions and setting up the film's climax.",
    thumbnail: "/placeholder.svg?height=720&width=1280&query=flooded%20basement%20parasite%20scene",
    duration: "4:10",
    movieId: "parasite",
    movieTitle: "Parasite",
    moviePoster: "/parasite-movie-poster.png",
    releaseYear: 2019,
    director: "Bong Joon-ho",
    cinematographer: "Hong Kyung-pyo",
    genres: ["drama", "thriller", "comedy"],
    sceneType: "emotional",
    viewCount: 12567,
    commentCount: 198,
    isPopular: false,
    isVisualTreat: false,
    addedDate: "2023-03-05T16:45:00Z",
  },
  {
    id: "scene-004",
    title: "Docking Scene",
    description:
      "A breathtaking sequence where the spacecraft attempts to dock with the rotating station, set to Hans Zimmer's intense score.",
    thumbnail: "/placeholder.svg?height=720&width=1280&query=space%20docking%20scene%20interstellar",
    duration: "5:30",
    movieId: "interstellar",
    movieTitle: "Interstellar",
    moviePoster: "/interstellar-poster.png",
    releaseYear: 2014,
    director: "Christopher Nolan",
    cinematographer: "Hoyte van Hoytema",
    genres: ["sci-fi", "drama", "adventure"],
    sceneType: "action",
    viewCount: 20145,
    commentCount: 287,
    isPopular: true,
    isVisualTreat: true,
    addedDate: "2023-01-28T11:20:00Z",
  },
  {
    id: "scene-005",
    title: "Peach Montage",
    description:
      "A beautifully shot sequence showing the meticulous preparation of the poisoned peach, highlighting the film's themes of deception.",
    thumbnail: "/placeholder.svg?height=720&width=1280&query=peach%20preparation%20parasite%20scene",
    duration: "2:15",
    movieId: "parasite",
    movieTitle: "Parasite",
    moviePoster: "/parasite-movie-poster.png",
    releaseYear: 2019,
    director: "Bong Joon-ho",
    cinematographer: "Hong Kyung-pyo",
    genres: ["drama", "thriller", "comedy"],
    sceneType: "dialogue",
    viewCount: 9876,
    commentCount: 145,
    isPopular: false,
    isVisualTreat: true,
    addedDate: "2023-04-12T08:30:00Z",
  },
  {
    id: "scene-006",
    title: "Tesseract Sequence",
    description:
      "The mind-bending climax where Cooper enters the tesseract and communicates across time and space through gravity.",
    thumbnail: "/placeholder.svg?height=720&width=1280&query=tesseract%20bookshelf%20scene%20interstellar",
    duration: "6:45",
    movieId: "interstellar",
    movieTitle: "Interstellar",
    moviePoster: "/interstellar-poster.png",
    releaseYear: 2014,
    director: "Christopher Nolan",
    cinematographer: "Hoyte van Hoytema",
    genres: ["sci-fi", "drama", "adventure"],
    sceneType: "emotional",
    viewCount: 22567,
    commentCount: 312,
    isPopular: true,
    isVisualTreat: true,
    addedDate: "2023-02-05T13:40:00Z",
  },
  {
    id: "scene-007",
    title: "Opening Heist",
    description:
      "The meticulously planned bank robbery that introduces the Joker and sets the tone for the entire film.",
    thumbnail: "/placeholder.svg?height=720&width=1280&query=bank%20heist%20joker%20dark%20knight",
    duration: "5:20",
    movieId: "dark-knight",
    movieTitle: "The Dark Knight",
    moviePoster: "/dark-knight-poster.png",
    releaseYear: 2008,
    director: "Christopher Nolan",
    cinematographer: "Wally Pfister",
    genres: ["action", "crime", "drama"],
    sceneType: "action",
    viewCount: 19876,
    commentCount: 267,
    isPopular: true,
    isVisualTreat: false,
    addedDate: "2023-03-18T10:15:00Z",
  },
  {
    id: "scene-008",
    title: "Interrogation Room",
    description:
      "The intense psychological confrontation between Batman and the Joker in the police interrogation room.",
    thumbnail: "/placeholder.svg?height=720&width=1280&query=batman%20joker%20interrogation%20scene",
    duration: "4:30",
    movieId: "dark-knight",
    movieTitle: "The Dark Knight",
    moviePoster: "/dark-knight-poster.png",
    releaseYear: 2008,
    director: "Christopher Nolan",
    cinematographer: "Wally Pfister",
    genres: ["action", "crime", "drama"],
    sceneType: "dialogue",
    viewCount: 21345,
    commentCount: 298,
    isPopular: true,
    isVisualTreat: false,
    addedDate: "2023-02-22T15:50:00Z",
  },
  {
    id: "scene-009",
    title: "Spinning Top Ending",
    description:
      "The ambiguous final shot that leaves viewers questioning whether Cobb is still in a dream or back in reality.",
    thumbnail: "/placeholder.svg?height=720&width=1280&query=spinning%20top%20inception%20ending",
    duration: "1:15",
    movieId: "inception",
    movieTitle: "Inception",
    moviePoster: "/inception-movie-poster.png",
    releaseYear: 2010,
    director: "Christopher Nolan",
    cinematographer: "Wally Pfister",
    genres: ["sci-fi", "action", "thriller"],
    sceneType: "emotional",
    viewCount: 25678,
    commentCount: 389,
    isPopular: true,
    isVisualTreat: false,
    addedDate: "2023-01-05T17:25:00Z",
  },
  {
    id: "scene-010",
    title: "Waves on Miller's Planet",
    description:
      "The awe-inspiring and terrifying sequence where the crew encounters massive tidal waves on a planet with extreme time dilation.",
    thumbnail: "/placeholder.svg?height=720&width=1280&query=giant%20tidal%20wave%20interstellar",
    duration: "3:50",
    movieId: "interstellar",
    movieTitle: "Interstellar",
    moviePoster: "/interstellar-poster.png",
    releaseYear: 2014,
    director: "Christopher Nolan",
    cinematographer: "Hoyte van Hoytema",
    genres: ["sci-fi", "drama", "adventure"],
    sceneType: "action",
    viewCount: 18432,
    commentCount: 245,
    isPopular: true,
    isVisualTreat: true,
    addedDate: "2023-04-02T12:10:00Z",
  },
  {
    id: "scene-011",
    title: "Jessica's Letter",
    description:
      "The emotional scene where Cooper watches decades of messages from his daughter, showcasing the film's theme of time and loss.",
    thumbnail: "/placeholder.svg?height=720&width=1280&query=cooper%20watching%20messages%20interstellar",
    duration: "4:15",
    movieId: "interstellar",
    movieTitle: "Interstellar",
    moviePoster: "/interstellar-poster.png",
    releaseYear: 2014,
    director: "Christopher Nolan",
    cinematographer: "Hoyte van Hoytema",
    genres: ["sci-fi", "drama", "adventure"],
    sceneType: "emotional",
    viewCount: 17654,
    commentCount: 276,
    isPopular: false,
    isVisualTreat: false,
    addedDate: "2023-03-28T09:45:00Z",
  },
  {
    id: "scene-012",
    title: "Bathroom Fight",
    description:
      "A brutal, realistic fight sequence in a bathroom that showcases the film's raw approach to action choreography.",
    thumbnail: "/placeholder.svg?height=720&width=1280&query=bathroom%20fight%20scene%20mission%20impossible",
    duration: "3:40",
    movieId: "mission-impossible-fallout",
    movieTitle: "Mission: Impossible - Fallout",
    moviePoster: "/placeholder.svg?height=600&width=400&query=mission%20impossible%20fallout%20poster",
    releaseYear: 2018,
    director: "Christopher McQuarrie",
    cinematographer: "Rob Hardy",
    genres: ["action", "adventure", "thriller"],
    sceneType: "action",
    viewCount: 15432,
    commentCount: 187,
    isPopular: false,
    isVisualTreat: false,
    addedDate: "2023-05-10T14:20:00Z",
  },
]
