/**
 * Mock data for User Reviews
 * 50+ reviews with varied ratings, lengths, spoilers, and verification status
 */

import { UserReview } from '@/types/review-page'

export const mockUserReviews: UserReview[] = [
  {
    id: 1,
    movie_id: 1,
    user: {
      username: 'john_doe',
      display_name: 'John Doe',
      avatar_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=john',
      is_verified: true,
    },
    rating: 5,
    content:
      'This movie changed my life. The themes of hope and redemption are beautifully woven throughout the entire film. Morgan Freeman and Tim Robbins deliver performances that will be remembered for generations. The ending brought tears to my eyes. An absolute masterpiece that everyone should watch at least once in their lifetime.',
    contains_spoilers: false,
    helpful_count: 247,
    unhelpful_count: 12,
    comment_count: 34,
    created_at: '2024-03-18T10:30:00Z',
    user_vote: null,
  },
  {
    id: 2,
    movie_id: 1,
    user: {
      username: 'movie_buff_2024',
      display_name: 'Movie Buff',
      avatar_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=buff',
      is_verified: false,
    },
    rating: 4,
    content:
      'Great film, but the pacing in the middle felt a bit slow. The performances are excellent, and the cinematography is stunning. Overall, a must-watch classic that lives up to its reputation.',
    contains_spoilers: false,
    helpful_count: 89,
    unhelpful_count: 23,
    comment_count: 12,
    created_at: '2024-03-17T14:20:00Z',
    user_vote: null,
  },
  {
    id: 3,
    movie_id: 1,
    user: {
      username: 'spoiler_alert',
      display_name: 'Spoiler Alert',
      avatar_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=spoiler',
      is_verified: true,
    },
    rating: 5,
    content:
      'The way Andy escapes through the tunnel he spent 20 years digging is absolutely brilliant! And when he stands in the rain after crawling through the sewage pipe - pure cinema! The reveal that he\'s been planning this for decades is mind-blowing. Red finding him on the beach in Zihuatanejo is the perfect ending.',
    contains_spoilers: true,
    helpful_count: 156,
    unhelpful_count: 45,
    comment_count: 28,
    created_at: '2024-03-16T09:15:00Z',
    user_vote: null,
  },
  {
    id: 4,
    movie_id: 1,
    user: {
      username: 'cinema_lover',
      display_name: 'Cinema Lover',
      avatar_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=cinema',
      is_verified: true,
    },
    rating: 5,
    content:
      'Perfection. Every single frame, every line of dialogue, every performance - all perfect. This is what cinema is all about.',
    contains_spoilers: false,
    helpful_count: 312,
    unhelpful_count: 8,
    comment_count: 45,
    created_at: '2024-03-15T16:45:00Z',
    user_vote: null,
  },
  {
    id: 5,
    movie_id: 1,
    user: {
      username: 'critical_viewer',
      display_name: 'Critical Viewer',
      avatar_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=critical',
      is_verified: false,
    },
    rating: 3,
    content:
      'It\'s a good movie, but I don\'t understand why it\'s rated #1 on IMDb. The story is predictable, and some scenes feel overly sentimental. Still worth watching, but not the masterpiece everyone claims it to be.',
    contains_spoilers: false,
    helpful_count: 45,
    unhelpful_count: 189,
    comment_count: 67,
    created_at: '2024-03-14T11:30:00Z',
    user_vote: null,
  },
  {
    id: 6,
    movie_id: 1,
    user: {
      username: 'first_time_watcher',
      display_name: 'First Time Watcher',
      avatar_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=first',
      is_verified: false,
    },
    rating: 5,
    content:
      'Just watched this for the first time and WOW! I can\'t believe I waited so long. The friendship between Andy and Red is so genuine and heartwarming. Cried at the end.',
    contains_spoilers: false,
    helpful_count: 178,
    unhelpful_count: 5,
    comment_count: 23,
    created_at: '2024-03-13T20:10:00Z',
    user_vote: null,
  },
  {
    id: 7,
    movie_id: 1,
    user: {
      username: 'morgan_freeman_fan',
      display_name: 'Morgan Freeman Fan',
      avatar_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=morgan',
      is_verified: true,
    },
    rating: 5,
    content:
      'Morgan Freeman\'s narration is the soul of this film. His voice is so soothing and wise. This is his best performance, hands down.',
    contains_spoilers: false,
    helpful_count: 234,
    unhelpful_count: 11,
    comment_count: 19,
    created_at: '2024-03-12T13:25:00Z',
    user_vote: null,
  },
  {
    id: 8,
    movie_id: 1,
    user: {
      username: 'disappointed_viewer',
      display_name: 'Disappointed Viewer',
      avatar_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=disappointed',
      is_verified: false,
    },
    rating: 2,
    content:
      'Overhyped. The movie is too long, the pacing is slow, and the ending is unrealistic. I expected more based on all the praise it gets.',
    contains_spoilers: false,
    helpful_count: 23,
    unhelpful_count: 267,
    comment_count: 89,
    created_at: '2024-03-11T08:40:00Z',
    user_vote: null,
  },
  {
    id: 9,
    movie_id: 1,
    user: {
      username: 'emotional_wreck',
      display_name: 'Emotional Wreck',
      avatar_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=emotional',
      is_verified: true,
    },
    rating: 5,
    content:
      'I\'ve watched this movie 10 times and I cry every single time. The scene where Brooks hangs himself breaks my heart. And the ending on the beach - pure joy. This film is an emotional rollercoaster.',
    contains_spoilers: true,
    helpful_count: 198,
    unhelpful_count: 7,
    comment_count: 31,
    created_at: '2024-03-10T17:55:00Z',
    user_vote: null,
  },
  {
    id: 10,
    movie_id: 1,
    user: {
      username: 'cinematography_nerd',
      display_name: 'Cinematography Nerd',
      avatar_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=cinematography',
      is_verified: true,
    },
    rating: 5,
    content:
      'Roger Deakins is a genius. The way he uses light and shadow to convey emotion is masterful. Every frame could be a painting.',
    contains_spoilers: false,
    helpful_count: 145,
    unhelpful_count: 3,
    comment_count: 15,
    created_at: '2024-03-09T12:30:00Z',
    user_vote: null,
  },
  {
    id: 11,
    movie_id: 1,
    user: {
      username: 'stephen_king_reader',
      display_name: 'Stephen King Reader',
      avatar_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=stephen',
      is_verified: false,
    },
    rating: 4,
    content:
      'Great adaptation of the novella. Darabont captured the essence of King\'s story perfectly. Some changes from the book, but they work well for the film.',
    contains_spoilers: false,
    helpful_count: 67,
    unhelpful_count: 12,
    comment_count: 8,
    created_at: '2024-03-08T15:20:00Z',
    user_vote: null,
  },
  {
    id: 12,
    movie_id: 1,
    user: {
      username: 'hope_believer',
      display_name: 'Hope Believer',
      avatar_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=hope',
      is_verified: true,
    },
    rating: 5,
    content:
      '"Hope is a good thing, maybe the best of things, and no good thing ever dies." This quote changed my perspective on life. Thank you for this masterpiece.',
    contains_spoilers: false,
    helpful_count: 289,
    unhelpful_count: 4,
    comment_count: 42,
    created_at: '2024-03-07T10:45:00Z',
    user_vote: null,
  },
  {
    id: 13,
    movie_id: 1,
    user: {
      username: 'tim_robbins_fan',
      display_name: 'Tim Robbins Fan',
      avatar_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=tim',
      is_verified: false,
    },
    rating: 5,
    content:
      'Tim Robbins brings such quiet strength to Andy. His performance is understated but incredibly powerful. One of the best actors of his generation.',
    contains_spoilers: false,
    helpful_count: 112,
    unhelpful_count: 6,
    comment_count: 14,
    created_at: '2024-03-06T14:10:00Z',
    user_vote: null,
  },
  {
    id: 14,
    movie_id: 1,
    user: {
      username: 'prison_drama_fan',
      display_name: 'Prison Drama Fan',
      avatar_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=prison',
      is_verified: true,
    },
    rating: 5,
    content:
      'The best prison drama ever made. It explores themes of institutionalization, friendship, and freedom with incredible depth.',
    contains_spoilers: false,
    helpful_count: 156,
    unhelpful_count: 8,
    comment_count: 21,
    created_at: '2024-03-05T09:30:00Z',
    user_vote: null,
  },
  {
    id: 15,
    movie_id: 1,
    user: {
      username: 'music_lover',
      display_name: 'Music Lover',
      avatar_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=music',
      is_verified: false,
    },
    rating: 5,
    content:
      'Thomas Newman\'s score is hauntingly beautiful. The music elevates every scene and stays with you long after the film ends.',
    contains_spoilers: false,
    helpful_count: 98,
    unhelpful_count: 2,
    comment_count: 11,
    created_at: '2024-03-04T16:20:00Z',
    user_vote: null,
  },
  {
    id: 16,
    movie_id: 1,
    user: {
      username: 'rewatcher',
      display_name: 'Rewatcher',
      avatar_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=rewatcher',
      is_verified: true,
    },
    rating: 5,
    content: 'Watched it 20+ times. Still discover new details every time. A film that rewards repeated viewing.',
    contains_spoilers: false,
    helpful_count: 134,
    unhelpful_count: 3,
    comment_count: 18,
    created_at: '2024-03-03T11:40:00Z',
    user_vote: null,
  },
  {
    id: 17,
    movie_id: 1,
    user: {
      username: 'young_viewer',
      display_name: 'Young Viewer',
      avatar_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=young',
      is_verified: false,
    },
    rating: 4,
    content: 'I\'m 18 and just watched this. It\'s old but still amazing. The story is timeless.',
    contains_spoilers: false,
    helpful_count: 56,
    unhelpful_count: 8,
    comment_count: 9,
    created_at: '2024-03-02T19:15:00Z',
    user_vote: null,
  },
  {
    id: 18,
    movie_id: 1,
    user: {
      username: 'brooks_was_here',
      display_name: 'Brooks Was Here',
      avatar_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=brooks',
      is_verified: true,
    },
    rating: 5,
    content: 'Brooks\' story is the most heartbreaking part. "I don\'t like it here. I\'m tired of being afraid all the time." Gets me every time.',
    contains_spoilers: true,
    helpful_count: 201,
    unhelpful_count: 6,
    comment_count: 27,
    created_at: '2024-03-01T14:50:00Z',
    user_vote: null,
  },
  {
    id: 19,
    movie_id: 1,
    user: {
      username: 'zihuatanejo_dreamer',
      display_name: 'Zihuatanejo Dreamer',
      avatar_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=zihua',
      is_verified: false,
    },
    rating: 5,
    content: 'I want to visit Zihuatanejo because of this movie. The beach scene is pure magic.',
    contains_spoilers: false,
    helpful_count: 87,
    unhelpful_count: 4,
    comment_count: 12,
    created_at: '2024-02-29T10:20:00Z',
    user_vote: null,
  },
  {
    id: 20,
    movie_id: 1,
    user: {
      username: 'opera_scene_lover',
      display_name: 'Opera Scene Lover',
      avatar_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=opera',
      is_verified: true,
    },
    rating: 5,
    content: 'The scene where Andy plays the opera over the loudspeakers is one of the most beautiful moments in cinema. Freedom through music.',
    contains_spoilers: false,
    helpful_count: 176,
    unhelpful_count: 2,
    comment_count: 22,
    created_at: '2024-02-28T15:35:00Z',
    user_vote: null,
  },
  {
    id: 21,
    movie_id: 1,
    user: {
      username: 'library_builder',
      display_name: 'Library Builder',
      avatar_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=library',
      is_verified: false,
    },
    rating: 5,
    content: 'Andy building the library is such an inspiring subplot. Education and knowledge as tools for freedom.',
    contains_spoilers: false,
    helpful_count: 92,
    unhelpful_count: 3,
    comment_count: 10,
    created_at: '2024-02-27T12:10:00Z',
    user_vote: null,
  },
  {
    id: 22,
    movie_id: 1,
    user: {
      username: 'rooftop_scene_fan',
      display_name: 'Rooftop Scene Fan',
      avatar_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=rooftop',
      is_verified: true,
    },
    rating: 5,
    content: 'The rooftop beer scene is perfection. "We sat and drank with the sun on our shoulders and felt like free men."',
    contains_spoilers: false,
    helpful_count: 143,
    unhelpful_count: 1,
    comment_count: 16,
    created_at: '2024-02-26T09:45:00Z',
    user_vote: null,
  },
  {
    id: 23,
    movie_id: 1,
    user: {
      username: 'patient_viewer',
      display_name: 'Patient Viewer',
      avatar_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=patient',
      is_verified: false,
    },
    rating: 4,
    content: 'Takes patience to watch, but it\'s worth it. The slow build makes the payoff even better.',
    contains_spoilers: false,
    helpful_count: 45,
    unhelpful_count: 12,
    comment_count: 7,
    created_at: '2024-02-25T16:30:00Z',
    user_vote: null,
  },
  {
    id: 24,
    movie_id: 1,
    user: {
      username: 'warden_hater',
      display_name: 'Warden Hater',
      avatar_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=warden',
      is_verified: true,
    },
    rating: 5,
    content: 'The warden is one of the best villains in cinema. His downfall is so satisfying to watch.',
    contains_spoilers: true,
    helpful_count: 118,
    unhelpful_count: 5,
    comment_count: 14,
    created_at: '2024-02-24T13:20:00Z',
    user_vote: null,
  },
  {
    id: 25,
    movie_id: 1,
    user: {
      username: 'geology_rocks',
      display_name: 'Geology Rocks',
      avatar_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=geology',
      is_verified: false,
    },
    rating: 5,
    content: '"Geology is the study of pressure and time. That\'s all it takes really, pressure, and time." This quote is brilliant.',
    contains_spoilers: false,
    helpful_count: 167,
    unhelpful_count: 3,
    comment_count: 19,
    created_at: '2024-02-23T10:55:00Z',
    user_vote: null,
  },
  {
    id: 26,
    movie_id: 1,
    user: {
      username: 'redemption_seeker',
      display_name: 'Redemption Seeker',
      avatar_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=redemption',
      is_verified: true,
    },
    rating: 5,
    content: 'This film taught me that redemption is always possible, no matter how dark things seem.',
    contains_spoilers: false,
    helpful_count: 203,
    unhelpful_count: 4,
    comment_count: 25,
    created_at: '2024-02-22T14:40:00Z',
    user_vote: null,
  },
  {
    id: 27,
    movie_id: 1,
    user: {
      username: 'friendship_goals',
      display_name: 'Friendship Goals',
      avatar_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=friendship',
      is_verified: false,
    },
    rating: 5,
    content: 'Andy and Red\'s friendship is what we all aspire to have. Genuine, loyal, and uplifting.',
    contains_spoilers: false,
    helpful_count: 189,
    unhelpful_count: 2,
    comment_count: 23,
    created_at: '2024-02-21T11:15:00Z',
    user_vote: null,
  },
  {
    id: 28,
    movie_id: 1,
    user: {
      username: 'tunnel_digger',
      display_name: 'Tunnel Digger',
      avatar_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=tunnel',
      is_verified: true,
    },
    rating: 5,
    content: 'The patience and determination Andy shows digging that tunnel for 20 years is mind-blowing. True perseverance.',
    contains_spoilers: true,
    helpful_count: 145,
    unhelpful_count: 7,
    comment_count: 17,
    created_at: '2024-02-20T15:50:00Z',
    user_vote: null,
  },
  {
    id: 29,
    movie_id: 1,
    user: {
      username: 'rain_scene_fan',
      display_name: 'Rain Scene Fan',
      avatar_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=rain',
      is_verified: false,
    },
    rating: 5,
    content: 'Andy standing in the rain after escaping is the most iconic scene. Pure freedom and joy.',
    contains_spoilers: true,
    helpful_count: 212,
    unhelpful_count: 3,
    comment_count: 28,
    created_at: '2024-02-19T09:30:00Z',
    user_vote: null,
  },
  {
    id: 30,
    movie_id: 1,
    user: {
      username: 'quote_collector',
      display_name: 'Quote Collector',
      avatar_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=quote',
      is_verified: true,
    },
    rating: 5,
    content: 'This movie has the best quotes. "Get busy living, or get busy dying." Words to live by.',
    contains_spoilers: false,
    helpful_count: 178,
    unhelpful_count: 2,
    comment_count: 21,
    created_at: '2024-02-18T13:45:00Z',
    user_vote: null,
  },
  {
    id: 31,
    movie_id: 1,
    user: {
      username: 'poster_collector',
      display_name: 'Poster Collector',
      avatar_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=poster',
      is_verified: false,
    },
    rating: 5,
    content: 'The poster hiding the tunnel is such a clever detail. Rita Hayworth, then Raquel Welch. Brilliant.',
    contains_spoilers: true,
    helpful_count: 98,
    unhelpful_count: 4,
    comment_count: 11,
    created_at: '2024-02-17T10:20:00Z',
    user_vote: null,
  },
  {
    id: 32,
    movie_id: 1,
    user: {
      username: 'tax_expert',
      display_name: 'Tax Expert',
      avatar_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=tax',
      is_verified: true,
    },
    rating: 5,
    content: 'Andy using his banking skills to help the guards is genius. It shows how knowledge is power.',
    contains_spoilers: false,
    helpful_count: 76,
    unhelpful_count: 3,
    comment_count: 8,
    created_at: '2024-02-16T14:35:00Z',
    user_vote: null,
  },
  {
    id: 33,
    movie_id: 1,
    user: {
      username: 'innocent_man',
      display_name: 'Innocent Man',
      avatar_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=innocent',
      is_verified: false,
    },
    rating: 5,
    content: 'The fact that Andy is actually innocent makes his story even more powerful. Justice delayed but not denied.',
    contains_spoilers: false,
    helpful_count: 134,
    unhelpful_count: 5,
    comment_count: 16,
    created_at: '2024-02-15T11:50:00Z',
    user_vote: null,
  },
  {
    id: 34,
    movie_id: 1,
    user: {
      username: 'tommy_williams_fan',
      display_name: 'Tommy Williams Fan',
      avatar_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=tommy',
      is_verified: true,
    },
    rating: 5,
    content: 'Tommy\'s death is heartbreaking. He was Andy\'s ticket to freedom and the warden took that away.',
    contains_spoilers: true,
    helpful_count: 112,
    unhelpful_count: 6,
    comment_count: 13,
    created_at: '2024-02-14T15:15:00Z',
    user_vote: null,
  },
  {
    id: 35,
    movie_id: 1,
    user: {
      username: 'sisters_hater',
      display_name: 'Sisters Hater',
      avatar_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=sisters',
      is_verified: false,
    },
    rating: 4,
    content: 'The scenes with the Sisters are hard to watch but necessary to show the brutality of prison life.',
    contains_spoilers: false,
    helpful_count: 67,
    unhelpful_count: 8,
    comment_count: 9,
    created_at: '2024-02-13T09:40:00Z',
    user_vote: null,
  },
  {
    id: 36,
    movie_id: 1,
    user: {
      username: 'heywood_fan',
      display_name: 'Heywood Fan',
      avatar_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=heywood',
      is_verified: true,
    },
    rating: 5,
    content: 'The supporting characters are all memorable. Heywood, Floyd, Skeet - they all add depth to the story.',
    contains_spoilers: false,
    helpful_count: 89,
    unhelpful_count: 2,
    comment_count: 10,
    created_at: '2024-02-12T13:25:00Z',
    user_vote: null,
  },
  {
    id: 37,
    movie_id: 1,
    user: {
      username: 'parole_board_scene',
      display_name: 'Parole Board Scene',
      avatar_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=parole',
      is_verified: false,
    },
    rating: 5,
    content: 'Red\'s final parole hearing is powerful. "Rehabilitated? It\'s just a bullshit word." Chills.',
    contains_spoilers: false,
    helpful_count: 156,
    unhelpful_count: 3,
    comment_count: 18,
    created_at: '2024-02-11T10:55:00Z',
    user_vote: null,
  },
  {
    id: 38,
    movie_id: 1,
    user: {
      username: 'compass_finder',
      display_name: 'Compass Finder',
      avatar_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=compass',
      is_verified: true,
    },
    rating: 5,
    content: 'The scene where Red finds the compass and money under the tree is so emotional. Andy kept his promise.',
    contains_spoilers: true,
    helpful_count: 187,
    unhelpful_count: 4,
    comment_count: 22,
    created_at: '2024-02-10T14:30:00Z',
    user_vote: null,
  },
  {
    id: 39,
    movie_id: 1,
    user: {
      username: 'buxton_visitor',
      display_name: 'Buxton Visitor',
      avatar_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=buxton',
      is_verified: false,
    },
    rating: 5,
    content: 'I visited Buxton, Maine because of this movie. The hayfield and oak tree are real!',
    contains_spoilers: false,
    helpful_count: 78,
    unhelpful_count: 5,
    comment_count: 12,
    created_at: '2024-02-09T11:45:00Z',
    user_vote: null,
  },
  {
    id: 40,
    movie_id: 1,
    user: {
      username: 'boat_restorer',
      display_name: 'Boat Restorer',
      avatar_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=boat',
      is_verified: true,
    },
    rating: 5,
    content: 'The ending with Andy working on the boat in Zihuatanejo is perfect. He finally found his paradise.',
    contains_spoilers: true,
    helpful_count: 143,
    unhelpful_count: 2,
    comment_count: 17,
    created_at: '2024-02-08T15:20:00Z',
    user_vote: null,
  },
  {
    id: 41,
    movie_id: 1,
    user: {
      username: 'chess_player',
      display_name: 'Chess Player',
      avatar_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=chess',
      is_verified: false,
    },
    rating: 5,
    content: 'Andy playing chess with himself is such a great metaphor for his strategic mind.',
    contains_spoilers: false,
    helpful_count: 92,
    unhelpful_count: 3,
    comment_count: 11,
    created_at: '2024-02-07T09:35:00Z',
    user_vote: null,
  },
  {
    id: 42,
    movie_id: 1,
    user: {
      username: 'rock_hammer_buyer',
      display_name: 'Rock Hammer Buyer',
      avatar_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=hammer',
      is_verified: true,
    },
    rating: 5,
    content: 'The rock hammer is the perfect symbol. What seems harmless becomes the tool of freedom.',
    contains_spoilers: true,
    helpful_count: 167,
    unhelpful_count: 4,
    comment_count: 19,
    created_at: '2024-02-06T13:50:00Z',
    user_vote: null,
  },
  {
    id: 43,
    movie_id: 1,
    user: {
      username: 'bible_reader',
      display_name: 'Bible Reader',
      avatar_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=bible',
      is_verified: false,
    },
    rating: 5,
    content: 'The warden telling Andy "Salvation lies within" while the hammer is hidden in the Bible is brilliant irony.',
    contains_spoilers: true,
    helpful_count: 198,
    unhelpful_count: 3,
    comment_count: 24,
    created_at: '2024-02-05T10:15:00Z',
    user_vote: null,
  },
  {
    id: 44,
    movie_id: 1,
    user: {
      username: 'bank_account_creator',
      display_name: 'Bank Account Creator',
      avatar_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=bank',
      is_verified: true,
    },
    rating: 5,
    content: 'Andy creating a fake identity and bank accounts is genius. He planned everything perfectly.',
    contains_spoilers: true,
    helpful_count: 145,
    unhelpful_count: 5,
    comment_count: 16,
    created_at: '2024-02-04T14:40:00Z',
    user_vote: null,
  },
  {
    id: 45,
    movie_id: 1,
    user: {
      username: 'ledger_keeper',
      display_name: 'Ledger Keeper',
      avatar_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=ledger',
      is_verified: false,
    },
    rating: 5,
    content: 'Andy sending the ledgers to the newspaper is the ultimate revenge. The warden\'s empire crumbles.',
    contains_spoilers: true,
    helpful_count: 176,
    unhelpful_count: 4,
    comment_count: 20,
    created_at: '2024-02-03T11:25:00Z',
    user_vote: null,
  },
  {
    id: 46,
    movie_id: 1,
    user: {
      username: 'suit_wearer',
      display_name: 'Suit Wearer',
      avatar_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=suit',
      is_verified: true,
    },
    rating: 5,
    content: 'Andy walking out of the bank in the warden\'s suit is such a power move. He took everything.',
    contains_spoilers: true,
    helpful_count: 189,
    unhelpful_count: 3,
    comment_count: 22,
    created_at: '2024-02-02T15:55:00Z',
    user_vote: null,
  },
  {
    id: 47,
    movie_id: 1,
    user: {
      username: 'postcard_receiver',
      display_name: 'Postcard Receiver',
      avatar_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=postcard',
      is_verified: false,
    },
    rating: 5,
    content: 'The postcard from Andy is the moment Red realizes his friend made it. So beautiful.',
    contains_spoilers: true,
    helpful_count: 156,
    unhelpful_count: 2,
    comment_count: 18,
    created_at: '2024-02-01T09:30:00Z',
    user_vote: null,
  },
  {
    id: 48,
    movie_id: 1,
    user: {
      username: 'bus_rider',
      display_name: 'Bus Rider',
      avatar_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=bus',
      is_verified: true,
    },
    rating: 5,
    content: 'Red\'s bus ride to Mexico is filled with hope and anticipation. You can feel his excitement.',
    contains_spoilers: true,
    helpful_count: 134,
    unhelpful_count: 3,
    comment_count: 15,
    created_at: '2024-01-31T13:45:00Z',
    user_vote: null,
  },
  {
    id: 49,
    movie_id: 1,
    user: {
      username: 'pacific_ocean_lover',
      display_name: 'Pacific Ocean Lover',
      avatar_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=pacific',
      is_verified: false,
    },
    rating: 5,
    content: '"The Pacific Ocean has no memory." This line gives me chills. A place where the past doesn\'t matter.',
    contains_spoilers: false,
    helpful_count: 167,
    unhelpful_count: 4,
    comment_count: 19,
    created_at: '2024-01-30T10:20:00Z',
    user_vote: null,
  },
  {
    id: 50,
    movie_id: 1,
    user: {
      username: 'final_embrace',
      display_name: 'Final Embrace',
      avatar_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=embrace',
      is_verified: true,
    },
    rating: 5,
    content: 'The final shot of Andy and Red embracing on the beach makes me cry every time. Perfect ending to a perfect film.',
    contains_spoilers: true,
    helpful_count: 234,
    unhelpful_count: 2,
    comment_count: 29,
    created_at: '2024-01-29T14:55:00Z',
    user_vote: null,
  },
]

