import type { Movie, MasterpieceFilm, SiddusPickMovie, CinematicVignette, TrendingPulse, BestScene } from "./types"

export const mockNewReleases: Movie[] = [
  {
    id: "nr1",
    title: "Dune: Part Two",
    posterUrl: "/dune-part-two-poster.png",
    slug: "dune-part-two",
    releaseDate: "2024-03-01",
    year: "2024",
    genres: ["Sci-Fi", "Adventure", "Drama"],
    rating: "PG-13",
    director: "Denis Villeneuve",
    duration: "2h 46m",
    description:
      "Paul Atreides unites with Chani and the Fremen while seeking revenge against the conspirators who destroyed his family.",
    averageRating: 4.7,
    sidduScore: 9.2,
    backdropUrl: "/dune-part-two-desert.png",
  },
  {
    id: "nr2",
    title: "Oppenheimer",
    posterUrl: "/oppenheimer-inspired-poster.png",
    slug: "oppenheimer",
    releaseDate: "2023-07-21",
    year: "2023",
    genres: ["Biography", "Drama", "History"],
    rating: "R",
    director: "Christopher Nolan",
    duration: "3h 0m",
    description:
      "The story of American scientist J. Robert Oppenheimer and his role in the development of the atomic bomb.",
    averageRating: 4.8,
    sidduScore: 9.0,
    backdropUrl: "/oppenheimer-backdrop.png",
  },
  {
    id: "nr3",
    title: "Barbie",
    posterUrl: "/barbie-movie-poster.png",
    slug: "barbie",
    releaseDate: "2023-07-21",
    year: "2023",
    genres: ["Comedy", "Fantasy", "Adventure"],
    rating: "PG-13",
    director: "Greta Gerwig",
    duration: "1h 54m",
    description: "Barbie suffers a crisis that leads her to question her world and her existence.",
    averageRating: 4.2,
    sidduScore: 7.9,
    backdropUrl: "/vibrant-pink-dreamhouse.png",
  },
  {
    id: "nr4",
    title: "Killers of the Flower Moon",
    posterUrl: "/killers-of-the-flower-moon-poster.png",
    slug: "killers-of-the-flower-moon",
    releaseDate: "2023-10-20",
    year: "2023",
    genres: ["Crime", "Drama", "History"],
    rating: "R",
    director: "Martin Scorsese",
    duration: "3h 26m",
    description:
      "Members of the Osage tribe in the United States are murdered under mysterious circumstances in the 1920s, sparking a major F.B.I. investigation involving J. Edgar Hoover.",
    averageRating: 4.5,
    sidduScore: 8.8,
    backdropUrl: "/killers-flower-moon-drama.png",
  },
]

export const mockMasterpieces: MasterpieceFilm[] = [
  {
    id: "mp1",
    title: "Parasite",
    posterUrl: "/parasite-movie-poster.png",
    slug: "parasite",
    releaseDate: "2019-05-30",
    year: "2019",
    genres: ["Drama", "Thriller", "Comedy"],
    rating: "R",
    director: "Bong Joon-ho",
    duration: "2h 12m",
    description:
      "Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.",
    averageRating: 4.9,
    sidduScore: 9.5,
    country: "South Korea",
    countryCode: "KR",
    visualStyle: "Contemporary Thriller",
    backdropUrl: "/placeholder.svg?width=1280&height=720",
  },
  {
    id: "mp2",
    title: "In the Mood for Love",
    posterUrl: "/in-the-mood-for-love-poster.png",
    slug: "in-the-mood-for-love",
    releaseDate: "2000-09-29",
    year: "2000",
    genres: ["Drama", "Romance"],
    rating: "PG",
    director: "Wong Kar-wai",
    duration: "1h 38m",
    description:
      "Two neighbors form a strong bond after both suspect extramarital activities of their spouses. However, they agree to keep their bond platonic so as not to commit similar wrongs.",
    averageRating: 4.8,
    sidduScore: 9.3,
    country: "Hong Kong",
    countryCode: "HK",
    visualStyle: "Romantic Arthous",
    backdropUrl: "/placeholder.svg?width=1280&height=720",
  },
  {
    id: "mp3",
    title: "Seven Samurai",
    posterUrl: "/seven-samurai-poster.png",
    slug: "seven-samurai",
    releaseDate: "1954-04-26",
    year: "1954",
    genres: ["Action", "Drama", "Adventure"],
    rating: "Not Rated",
    director: "Akira Kurosawa",
    duration: "3h 27m",
    description:
      "A poor village under attack by bandits recruits seven unemployed samurai to help them defend themselves.",
    averageRating: 4.9,
    sidduScore: 9.8,
    country: "Japan",
    countryCode: "JP",
    visualStyle: "Classic Epic",
    backdropUrl: "/placeholder.svg?width=1280&height=720",
  },
]

export const mockSiddusPicks: SiddusPickMovie[] = [
  {
    id: "sp1",
    title: "Blade Runner 2049",
    posterUrl: "/blade-runner-2049-poster.png",
    backdropUrl: "/dramatic-city-rooftop.png",
    releaseDate: "2017-10-06",
    year: "2017",
    genres: ["Sci-Fi", "Neo-noir", "Drama"],
    rating: "R",
    director: "Denis Villeneuve",
    duration: "2h 44m",
    slug: "blade-runner-2049",
    description:
      "Officer K, a new blade runner for the Los Angeles Police Department, unearths a long-buried secret that has the potential to plunge what's left of society into chaos.",
    averageRating: 4.7,
    sidduScore: 9.1,
    pickReason:
      "A visually stunning sequel that expands on the original's themes with breathtaking cinematography and a compelling narrative. Pure cinematic art.",
  },
  {
    id: "sp2",
    title: "Mad Max: Fury Road",
    posterUrl: "/mad-max-fury-road-poster.png",
    backdropUrl: "/dystopian-car-chase.png",
    releaseDate: "2015-05-15",
    year: "2015",
    genres: ["Action", "Sci-Fi", "Adventure"],
    rating: "R",
    director: "George Miller",
    duration: "2h 0m",
    slug: "mad-max-fury-road",
    description:
      "In a post-apocalyptic wasteland, a woman rebels against a tyrannical ruler in search for her homeland with the help of a group of female prisoners, a psychotic worshiper, and a drifter named Max.",
    averageRating: 4.8,
    sidduScore: 9.3,
    pickReason:
      "A relentless, adrenaline-fueled masterpiece of action filmmaking with incredible practical effects and world-building. Non-stop intensity.",
  },
  {
    id: "sp3",
    title: "Arrival",
    posterUrl: "/arrival-poster.png",
    backdropUrl: "/placeholder.svg?width=1280&height=720",
    releaseDate: "2016-11-11",
    year: "2016",
    genres: ["Sci-Fi", "Drama", "Mystery"],
    rating: "PG-13",
    director: "Denis Villeneuve",
    duration: "1h 56m",
    slug: "arrival",
    description:
      "A linguist works with the military to communicate with alien lifeforms after twelve mysterious spacecraft appear around the world.",
    averageRating: 4.6,
    sidduScore: 9.0,
    pickReason:
      "Intelligent, thought-provoking science fiction that focuses on communication and humanity. Emotionally resonant and visually captivating.",
  },
]

export const mockVignetteData: CinematicVignette = {
  id: "inception-vignette",
  title: "Inception",
  director: "Christopher Nolan",
  year: "2010",
  quote: "Your mind is the scene of the crime.",
  quoteAuthor: "Cobb (Leonardo DiCaprio)",
  description:
    "A mind-bending thriller that explores the depths of the subconscious, Inception redefined the heist genre with its intricate dream-within-a-dream narrative and stunning visual effects. A true cinematic experience that challenges perceptions of reality.",
  videoUrl: "https://www.youtube.com/embed/YoHD9XEInc0",
  fallbackImageUrl: "/dark-blue-city-skyline.png",
  ctaText: "Explore Inception",
  ctaLink: "/movies/inception",
  theme: "dark",
  category: "Iconic Film",
  elements: [
    {
      type: "image",
      src: "/inception-scene-thumbnail.png",
      alt: "Inception Paris Folding Scene",
      position: { top: "15%", left: "10%" },
      animation: { type: "fadeInLeft", delay: 0.3, duration: 0.8 },
      className: "w-1/4 md:w-1/5 rounded-lg shadow-2xl",
    },
    {
      type: "image",
      src: "/inception-spinning-top.png",
      alt: "Inception Spinning Top",
      position: { bottom: "20%", right: "12%" },
      animation: { type: "fadeInRight", delay: 0.5, duration: 0.8 },
      className: "w-16 h-16 md:w-20 md:h-20",
    },
    {
      type: "text",
      content: "Dream within a dream",
      position: { top: "25%", right: "15%" },
      animation: { type: "fadeInDown", delay: 0.7, duration: 0.8 },
      className: "text-xl md:text-2xl font-semibold text-gray-200 shadow-text",
    },
  ],
}

export const mockTrendingPulses: TrendingPulse[] = [
  {
    id: "pulse1",
    user: {
      name: "CinemaBuff",
      username: "cinemabuff",
      avatarUrl: "/user-avatar-1.png",
      isVerified: true,
    },
    content:
      "Just saw Dune: Part Two. Absolutely breathtaking visuals and score! Villeneuve is a master. #DunePartTwo #SciFi",
    media: [{ type: "image", url: "/dune-part-two-desert.png", alt: "Dune Part Two Scene" }],
    timestamp: new Date(Date.now() - 3600000 * 2).toISOString(),
    stats: { likes: 156, comments: 23, reposts: 12, views: 1200 },
    tags: ["DunePartTwo", "SciFi", "MovieReview"],
    sourceMovieId: "nr1",
  },
  {
    id: "pulse2",
    user: {
      name: "CricketFanatic",
      username: "cricfan",
      avatarUrl: "/user-avatar-2.png",
    },
    content:
      "What a match! India vs Australia was a nail-biter till the end. Virat Kohli masterclass! #INDvsAUS #Cricket #KingKohli",
    timestamp: new Date(Date.now() - 3600000 * 5).toISOString(),
    stats: { likes: 205, comments: 45, reposts: 30, views: 2500 },
    tags: ["INDvsAUS", "Cricket", "Sports", "KingKohli"],
    media: [{ type: "image", url: "/cricket/ind-aus-series.png", alt: "India vs Australia Cricket Match" }],
  },
  {
    id: "pulse3",
    user: {
      name: "NolanFanGirl",
      username: "nolan_obsessed",
      avatarUrl: "/user-avatar-3.png",
      isVerified: true,
    },
    content:
      "Oppenheimer's sound design was phenomenal. The Trinity Test scene gave me chills. #Oppenheimer #ChristopherNolan",
    timestamp: new Date(Date.now() - 3600000 * 8).toISOString(),
    stats: { likes: 310, comments: 55, reposts: 40, views: 3200 },
    tags: ["Oppenheimer", "Nolan", "SoundDesign"],
    sourceMovieId: "nr2",
  },
]

export const mockBestScenes: BestScene[] = [
  {
    id: "scene1",
    movieId: "inception",
    movieTitle: "Inception",
    movieYear: "2010",
    title: "Paris Folding Cityscape", // Renamed from sceneTitle
    thumbnailUrl: "/inception-scene-thumbnail.png",
    description:
      "Ariadne learns to manipulate dream architecture, folding Paris onto itself in a breathtaking visual display of impossible geometry.",
    vfxBreakdown: true,
    directorInsight: false,
    duration: "2:35",
    sidduScore: 9.8,
    tags: ["Visual Effects", "Dream Logic", "Iconic Moment"],
    slug: "inception-paris-fold",
    timestampInMovie: "00:45:12",
  },
  {
    id: "scene2",
    movieId: "dark-knight",
    movieTitle: "The Dark Knight",
    movieYear: "2008",
    title: "Joker's Interrogation", // Renamed from sceneTitle
    thumbnailUrl: "/placeholder.svg?width=400&height=225",
    description:
      "Batman's intense confrontation with the Joker, a masterclass in psychological tension and unforgettable performances.",
    vfxBreakdown: false,
    directorInsight: true,
    duration: "5:12",
    sidduScore: 9.9,
    tags: ["Interrogation", "Psychological", "Heath Ledger"],
    slug: "dark-knight-joker-interrogation",
    timestampInMovie: "01:20:30",
  },
  {
    id: "scene3",
    movieId: "mad-max-fury-road",
    movieTitle: "Mad Max: Fury Road",
    movieYear: "2015",
    title: "The Sandstorm Chase", // Renamed from sceneTitle
    thumbnailUrl: "/placeholder.svg?width=400&height=225",
    description:
      "A visually spectacular and chaotic chase through a colossal sandstorm, showcasing incredible practical effects and vehicle designs.",
    vfxBreakdown: true,
    directorInsight: true,
    duration: "4:50",
    sidduScore: 9.7,
    tags: ["Action", "Practical Effects", "Chase Scene"],
    slug: "mad-max-sandstorm-chase",
    timestampInMovie: "00:35:50",
  },
]
