import type { PlayerProfile } from "./types"

export const getMockPlayerData = (id: string): PlayerProfile => {
  // This would normally fetch from an API, but for demo purposes we'll return mock data
  return {
    id,
    name: "Virat Kohli",
    fullName: "Virat Kohli",
    dateOfBirth: "November 5, 1988",
    placeOfBirth: "Delhi, India",
    nationality: "Indian",
    role: "Batsman",
    battingStyle: "Right-handed",
    bowlingStyle: "Right-arm medium",
    teams: [
      {
        id: "ind",
        name: "India",
        shortName: "IND",
        logoUrl: "/cricket/india-logo.png",
      },
      {
        id: "rcb",
        name: "Royal Challengers Bangalore",
        shortName: "RCB",
        logoUrl: "/generic-cricket-team-logo.png",
      },
    ],
    teamColors: {
      primary: "#0033A0",
      secondary: "#FF9933",
    },
    biography:
      "Virat Kohli is an Indian international cricketer and the former captain of the Indian national cricket team. He is widely regarded as one of the greatest batsmen in the history of cricket and the best of the current generation. Kohli plays for Delhi in domestic cricket and Royal Challengers Bangalore in the Indian Premier League as a right-handed batsman. He has been the recipient of many awards, including the Sir Garfield Sobers Trophy (ICC Men's Cricketer of the Decade): 2011–2020; ICC Men's ODI Cricketer of the Decade: 2011–2020; Wisden Leading Cricketer in the World for three consecutive years (2016, 2017 and 2018); ICC Cricketer of the Year (2017, 2018); ICC Test Player of the Year (2018); ICC ODI Player of the Year (2012, 2017, 2018) and Wisden Cricketers of the Year (2019).",
    careerSpan: "2008 - Present",
    imageUrl: "/cricket/virat-kohli.png",
    socialMedia: {
      twitter: "https://twitter.com/imVkohli",
      instagram: "https://www.instagram.com/virat.kohli/",
      facebook: "https://www.facebook.com/virat.kohli",
    },
    statistics: {
      batting: {
        matches: 492,
        innings: 516,
        runs: 25433,
        average: 53.5,
        strikeRate: 93.7,
        highestScore: 254,
        notOuts: 39,
        centuries: 74,
        halfCenturies: 129,
        fours: 2356,
        sixes: 420,
        formats: {
          test: {
            matches: 111,
            innings: 187,
            runs: 8676,
            average: 49.3,
            strikeRate: 57.5,
            highestScore: 254,
            notOuts: 11,
            centuries: 29,
            halfCenturies: 29,
            fours: 966,
            sixes: 24,
          },
          odi: {
            matches: 275,
            innings: 265,
            runs: 12898,
            average: 57.32,
            strikeRate: 93.62,
            highestScore: 183,
            notOuts: 40,
            centuries: 46,
            halfCenturies: 65,
            fours: 1211,
            sixes: 140,
          },
          t20: {
            matches: 115,
            innings: 107,
            runs: 3932,
            average: 52.73,
            strikeRate: 137.96,
            highestScore: 122,
            notOuts: 30,
            centuries: 1,
            halfCenturies: 37,
            fours: 356,
            sixes: 119,
          },
        },
        yearlyStats: [
          { year: 2018, runs: 2735, average: 68.37, centuries: 11, halfCenturies: 9 },
          { year: 2019, runs: 2455, average: 64.6, centuries: 7, halfCenturies: 14 },
          { year: 2020, runs: 842, average: 36.6, centuries: 0, halfCenturies: 7 },
          { year: 2021, runs: 964, average: 37.07, centuries: 0, halfCenturies: 8 },
          { year: 2022, runs: 1348, average: 38.51, centuries: 4, halfCenturies: 8 },
          { year: 2023, runs: 2048, average: 66.06, centuries: 8, halfCenturies: 8 },
        ],
      },
      bowling: {
        matches: 492,
        innings: 86,
        wickets: 8,
        average: 41.25,
        economy: 5.97,
        bestBowling: "2/25",
        fiveWicketHauls: 0,
        formats: {
          test: {
            matches: 111,
            innings: 12,
            wickets: 0,
            average: 0,
            economy: 4.86,
            bestBowling: "0/16",
          },
          odi: {
            matches: 275,
            innings: 50,
            wickets: 4,
            average: 166.25,
            economy: 6.22,
            bestBowling: "1/15",
          },
          t20: {
            matches: 115,
            innings: 24,
            wickets: 4,
            average: 77.0,
            economy: 8.0,
            bestBowling: "1/13",
          },
        },
        yearlyStats: [
          { year: 2018, wickets: 0, average: 0, economy: 0 },
          { year: 2019, wickets: 1, average: 42.0, economy: 5.25 },
          { year: 2020, wickets: 0, average: 0, economy: 0 },
          { year: 2021, wickets: 0, average: 0, economy: 0 },
          { year: 2022, wickets: 0, average: 0, economy: 0 },
          { year: 2023, wickets: 0, average: 0, economy: 0 },
        ],
      },
      fielding: {
        catches: 296,
        stumpings: 0,
        runOuts: 42,
      },
    },
    careerHighlights: {
      batting: [
        {
          title: "254 vs South Africa",
          description: "Career-best Test score against South Africa in Pune",
          date: "October 10, 2019",
          opponent: "South Africa",
          venue: "Pune, India",
          imageUrl: "/placeholder-hh7zk.png",
        },
        {
          title: "183 vs Pakistan",
          description: "Highest ODI score, chasing 330 in Asia Cup",
          date: "March 18, 2012",
          opponent: "Pakistan",
          venue: "Dhaka, Bangladesh",
          imageUrl: "/placeholder-13fek.png",
        },
        {
          title: "122* vs Afghanistan",
          description: "First T20I century, ending a century drought",
          date: "September 8, 2022",
          opponent: "Afghanistan",
          venue: "Dubai, UAE",
          imageUrl: "/placeholder-9ow8q.png",
        },
        {
          title: "82* vs Pakistan",
          description: "Match-winning knock in T20 World Cup 2022",
          date: "October 23, 2022",
          opponent: "Pakistan",
          venue: "Melbourne, Australia",
          imageUrl: "/placeholder-9vi85.png",
        },
      ],
    },
    matchHistory: [
      {
        id: "match1",
        date: "November 15, 2023",
        format: "ODI",
        teams: {
          home: {
            id: "ind",
            name: "India",
            shortName: "IND",
            logoUrl: "/cricket/india-logo.png",
          },
          away: {
            id: "aus",
            name: "Australia",
            shortName: "AUS",
            logoUrl: "/cricket/australia-logo.png",
          },
        },
        venue: "Mumbai, India",
        result: "India won by 5 wickets",
        playerPerformance: {
          batting: {
            runs: 85,
            balls: 92,
            fours: 8,
            sixes: 2,
            strikeRate: 92.39,
          },
        },
      },
      {
        id: "match2",
        date: "November 10, 2023",
        format: "ODI",
        teams: {
          home: {
            id: "ind",
            name: "India",
            shortName: "IND",
            logoUrl: "/cricket/india-logo.png",
          },
          away: {
            id: "aus",
            name: "Australia",
            shortName: "AUS",
            logoUrl: "/cricket/australia-logo.png",
          },
        },
        venue: "Delhi, India",
        result: "Australia won by 3 wickets",
        playerPerformance: {
          batting: {
            runs: 47,
            balls: 65,
            fours: 3,
            sixes: 1,
            strikeRate: 72.31,
          },
        },
      },
      {
        id: "match3",
        date: "November 5, 2023",
        format: "ODI",
        teams: {
          home: {
            id: "ind",
            name: "India",
            shortName: "IND",
            logoUrl: "/cricket/india-logo.png",
          },
          away: {
            id: "nz",
            name: "New Zealand",
            shortName: "NZ",
            logoUrl: "/cricket/new-zealand-logo.png",
          },
        },
        venue: "Chennai, India",
        result: "India won by 7 wickets",
        playerPerformance: {
          batting: {
            runs: 117,
            balls: 106,
            fours: 9,
            sixes: 4,
            strikeRate: 110.38,
          },
        },
      },
    ],
    awards: [
      {
        title: "ICC ODI Cricketer of the Year",
        year: "2017",
        description: "Awarded for exceptional performance in ODI cricket during 2017",
        imageUrl: "/placeholder-22pke.png",
      },
      {
        title: "Rajiv Gandhi Khel Ratna Award",
        year: "2018",
        description: "India's highest sporting honor",
        imageUrl: "/khel-ratna-award.png",
      },
      {
        title: "Wisden Leading Cricketer in the World",
        year: "2016, 2017, 2018",
        description: "Named Wisden's Leading Cricketer in the World for three consecutive years",
        imageUrl: "/placeholder.svg?height=200&width=200&query=Wisden Trophy",
      },
      {
        title: "ICC Men's Cricketer of the Decade",
        year: "2011-2020",
        description: "Awarded for outstanding achievements across all formats during the decade",
        imageUrl: "/placeholder.svg?height=200&width=200&query=ICC Decade Award",
      },
    ],
  }
}

export const mockPlayerIds = ["virat-kohli", "rohit-sharma", "jasprit-bumrah"]
