import type { MovieType } from "./types"
import { v4 as uuidv4 } from "uuid"

export const mockMovies: MovieType[] = [
  {
    id: uuidv4(),
    title: "Oppenheimer",
    year: "2023",
    releaseDate: "2023-07-21",
    posterUrl: "/oppenheimer-inspired-poster.png",
    backdropUrl: "/dramatic-oppenheimer.png",
    rating: 8.5,
    runtime: 180,
    overview:
      "The story of American scientist J. Robert Oppenheimer and his role in the development of the atomic bomb.",
    genres: ["Biography", "Drama", "History"],
    language: "English",
    country: "United States",
    director: "Christopher Nolan",
    cast: ["Cillian Murphy", "Emily Blunt", "Matt Damon", "Robert Downey Jr."],
    trending: true,
  },
  {
    id: uuidv4(),
    title: "Dune: Part Two",
    year: "2024",
    releaseDate: "2024-03-01",
    posterUrl: "/dune-part-two-poster.png",
    rating: 8.7,
    runtime: 166,
    overview:
      "Paul Atreides unites with Chani and the Fremen while seeking revenge against the conspirators who destroyed his family.",
    genres: ["Action", "Adventure", "Sci-Fi"],
    language: "English",
    country: "United States",
    director: "Denis Villeneuve",
    cast: ["Timothée Chalamet", "Zendaya", "Rebecca Ferguson", "Javier Bardem"],
    tags: ["visual_treat"],
    trending: true,
  },
  {
    id: uuidv4(),
    title: "Poor Things",
    year: "2023",
    releaseDate: "2023-12-08",
    posterUrl: "/poor-things-poster.png",
    rating: 8.3,
    runtime: 141,
    overview:
      "The incredible tale about the fantastical evolution of Bella Baxter, a young woman brought back to life by the brilliant and unorthodox scientist Dr. Godwin Baxter.",
    genres: ["Comedy", "Drama", "Romance", "Sci-Fi"],
    language: "English",
    country: "United Kingdom",
    director: "Yorgos Lanthimos",
    cast: ["Emma Stone", "Mark Ruffalo", "Willem Dafoe"],
    tags: ["visual_treat"],
    trending: true,
  },
  {
    id: uuidv4(),
    title: "Challengers",
    year: "2024",
    releaseDate: "2024-04-26",
    posterUrl: "/challengers-poster.png",
    backdropUrl: "/challengers-tennis-match.png",
    rating: 7.8,
    runtime: 131,
    overview:
      "Follows three players who knew each other when they were teenagers as they compete in a tennis tournament to be the world-famous grand slam winner, and reignite old rivalries on and off the court.",
    genres: ["Drama", "Romance", "Sport"],
    language: "English",
    country: "United States",
    director: "Luca Guadagnino",
    cast: ["Zendaya", "Josh O'Connor", "Mike Faist"],
    trending: true,
  },
  {
    id: uuidv4(),
    title: "Parasite",
    year: "2019",
    releaseDate: "2019-10-11",
    posterUrl: "/parasite-movie-poster.png",
    rating: 8.6,
    runtime: 132,
    overview:
      "Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.",
    genres: ["Comedy", "Drama", "Thriller"],
    language: "Korean",
    country: "South Korea",
    director: "Bong Joon-ho",
    cast: ["Song Kang-ho", "Lee Sun-kyun", "Cho Yeo-jeong"],
    tags: ["visual_treat"],
  },
  {
    id: uuidv4(),
    title: "Inception",
    year: "2010",
    releaseDate: "2010-07-16",
    posterUrl: "/inception-movie-poster.png",
    rating: 8.8,
    runtime: 148,
    overview:
      "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.",
    genres: ["Action", "Adventure", "Sci-Fi", "Thriller"],
    language: "English",
    country: "United States",
    director: "Christopher Nolan",
    cast: ["Leonardo DiCaprio", "Joseph Gordon-Levitt", "Elliot Page"],
    tags: ["visual_treat"],
  },
  {
    id: uuidv4(),
    title: "The Shawshank Redemption",
    year: "1994",
    releaseDate: "1994-09-23",
    posterUrl: "/shawshank-redemption-poster.png",
    rating: 9.3,
    runtime: 142,
    overview:
      "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.",
    genres: ["Drama"],
    language: "English",
    country: "United States",
    director: "Frank Darabont",
    cast: ["Tim Robbins", "Morgan Freeman", "Bob Gunton"],
  },
  {
    id: uuidv4(),
    title: "Pulp Fiction",
    year: "1994",
    releaseDate: "1994-10-14",
    posterUrl: "/pulp-fiction-poster.png",
    rating: 8.9,
    runtime: 154,
    overview:
      "The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.",
    genres: ["Crime", "Drama"],
    language: "English",
    country: "United States",
    director: "Quentin Tarantino",
    cast: ["John Travolta", "Uma Thurman", "Samuel L. Jackson"],
  },
  {
    id: uuidv4(),
    title: "The Dark Knight",
    year: "2008",
    releaseDate: "2008-07-18",
    posterUrl: "/dark-knight-poster.png",
    rating: 9.0,
    runtime: 152,
    overview:
      "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.",
    genres: ["Action", "Crime", "Drama", "Thriller"],
    language: "English",
    country: "United States",
    director: "Christopher Nolan",
    cast: ["Christian Bale", "Heath Ledger", "Aaron Eckhart"],
  },
  {
    id: uuidv4(),
    title: "Pather Panchali",
    year: "1955",
    releaseDate: "1955-08-26",
    posterUrl: "/pather-panchali-poster.png",
    rating: 8.6,
    runtime: 125,
    overview:
      "Impoverished priest Harihar Ray, dreaming of a better life for himself and his family, leaves his rural Bengal village in search of work.",
    genres: ["Drama"],
    language: "Bengali",
    country: "India",
    director: "Satyajit Ray",
    cast: ["Kanu Bannerjee", "Karuna Bannerjee", "Subir Banerjee"],
  },
  {
    id: uuidv4(),
    title: "Seven Samurai",
    year: "1954",
    releaseDate: "1954-04-26",
    posterUrl: "/placeholder.svg?height=600&width=400&query=seven samurai movie poster",
    rating: 8.6,
    runtime: 207,
    overview:
      "A poor village under attack by bandits recruits seven unemployed samurai to help them defend themselves.",
    genres: ["Action", "Adventure", "Drama"],
    language: "Japanese",
    country: "Japan",
    director: "Akira Kurosawa",
    cast: ["Toshiro Mifune", "Takashi Shimura", "Keiko Tsushima"],
  },
  {
    id: uuidv4(),
    title: "In the Mood for Love",
    year: "2000",
    releaseDate: "2000-09-29",
    posterUrl: "/in-the-mood-for-love-poster.png",
    rating: 8.1,
    runtime: 98,
    overview:
      "Two neighbors form a strong bond after both suspect extramarital activities of their spouses. However, they agree to keep their bond platonic so as not to commit similar wrongs.",
    genres: ["Drama", "Romance"],
    language: "Cantonese",
    country: "Hong Kong",
    director: "Wong Kar-wai",
    cast: ["Tony Leung Chiu-wai", "Maggie Cheung", "Ping Lam Siu"],
    tags: ["visual_treat"],
  },
  {
    id: uuidv4(),
    title: "City of God",
    year: "2002",
    releaseDate: "2002-05-18",
    posterUrl: "/city-of-god-poster.png",
    rating: 8.6,
    runtime: 130,
    overview:
      "In the slums of Rio, two kids' paths diverge as one struggles to become a photographer and the other a kingpin.",
    genres: ["Crime", "Drama"],
    language: "Portuguese",
    country: "Brazil",
    director: "Fernando Meirelles",
    cast: ["Alexandre Rodrigues", "Leandro Firmino", "Matheus Nachtergaele"],
    tags: ["visual_treat"],
  },
  {
    id: uuidv4(),
    title: "Amélie",
    year: "2001",
    releaseDate: "2001-04-25",
    posterUrl: "/placeholder.svg?height=600&width=400&query=amelie movie poster",
    rating: 8.3,
    runtime: 122,
    overview:
      "Amélie is an innocent and naive girl in Paris with her own sense of justice. She decides to help those around her and, along the way, discovers love.",
    genres: ["Comedy", "Romance"],
    language: "French",
    country: "France",
    director: "Jean-Pierre Jeunet",
    cast: ["Audrey Tautou", "Mathieu Kassovitz", "Rufus"],
    tags: ["visual_treat"],
  },
  {
    id: uuidv4(),
    title: "Pan's Labyrinth",
    year: "2006",
    releaseDate: "2006-10-11",
    posterUrl: "/placeholder.svg?height=600&width=400&query=pans labyrinth movie poster",
    rating: 8.2,
    runtime: 118,
    overview:
      "In the Falangist Spain of 1944, the bookish young stepdaughter of a sadistic army officer escapes into an eerie but captivating fantasy world.",
    genres: ["Drama", "Fantasy", "War"],
    language: "Spanish",
    country: "Spain",
    director: "Guillermo del Toro",
    cast: ["Ivana Baquero", "Ariadna Gil", "Sergi López"],
    tags: ["visual_treat"],
  },
  {
    id: uuidv4(),
    title: "Spirited Away",
    year: "2001",
    releaseDate: "2001-07-20",
    posterUrl: "/placeholder.svg?height=600&width=400&query=spirited away movie poster",
    rating: 8.6,
    runtime: 125,
    overview:
      "During her family's move to the suburbs, a sullen 10-year-old girl wanders into a world ruled by gods, witches, and spirits, and where humans are changed into beasts.",
    genres: ["Animation", "Adventure", "Family", "Fantasy"],
    language: "Japanese",
    country: "Japan",
    director: "Hayao Miyazaki",
    cast: ["Rumi Hiiragi", "Miyu Irino", "Mari Natsuki"],
    tags: ["visual_treat"],
  },
  {
    id: uuidv4(),
    title: "The Godfather",
    year: "1972",
    releaseDate: "1972-03-24",
    posterUrl: "/classic-mob-poster.png",
    rating: 9.2,
    runtime: 175,
    overview:
      "The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.",
    genres: ["Crime", "Drama"],
    language: "English",
    country: "United States",
    director: "Francis Ford Coppola",
    cast: ["Marlon Brando", "Al Pacino", "James Caan"],
  },
  {
    id: uuidv4(),
    title: "Citizen Kane",
    year: "1941",
    releaseDate: "1941-09-05",
    posterUrl: "/placeholder.svg?height=600&width=400&query=citizen kane movie poster",
    rating: 8.3,
    runtime: 119,
    overview:
      "Following the death of publishing tycoon Charles Foster Kane, reporters scramble to uncover the meaning of his final utterance; 'Rosebud'.",
    genres: ["Drama", "Mystery"],
    language: "English",
    country: "United States",
    director: "Orson Welles",
    cast: ["Orson Welles", "Joseph Cotten", "Dorothy Comingore"],
  },
  {
    id: uuidv4(),
    title: "Ran",
    year: "1985",
    releaseDate: "1985-06-01",
    posterUrl: "/placeholder.svg?height=600&width=400&query=ran kurosawa movie poster",
    rating: 8.2,
    runtime: 162,
    overview:
      "In Medieval Japan, an elderly warlord retires, handing over his empire to his three sons. However, he vastly underestimates how the new-found power will corrupt them and cause them to turn on each other...and him.",
    genres: ["Action", "Drama", "War"],
    language: "Japanese",
    country: "Japan",
    director: "Akira Kurosawa",
    cast: ["Tatsuya Nakadai", "Akira Terao", "Jinpachi Nezu"],
    tags: ["visual_treat"],
  },
  {
    id: uuidv4(),
    title: "The 400 Blows",
    year: "1959",
    releaseDate: "1959-06-03",
    posterUrl: "/the-400-blows-poster.png",
    rating: 8.1,
    runtime: 99,
    overview: "A young boy, left without attention, delves into a life of petty crime.",
    genres: ["Crime", "Drama"],
    language: "French",
    country: "France",
    director: "François Truffaut",
    cast: ["Jean-Pierre Léaud", "Albert Rémy", "Claire Maurier"],
  },
  {
    id: uuidv4(),
    title: "Interstellar",
    year: "2014",
    releaseDate: "2014-11-07",
    posterUrl: "/interstellar-poster.png",
    rating: 8.6,
    runtime: 169,
    overview: "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.",
    genres: ["Adventure", "Drama", "Sci-Fi"],
    language: "English",
    country: "United States",
    director: "Christopher Nolan",
    cast: ["Matthew McConaughey", "Anne Hathaway", "Jessica Chastain"],
    tags: ["visual_treat"],
  },
]
