import type { VisualTreat, AvailableFilters } from "./types"

export const MOCK_VISUAL_TREATS: VisualTreat[] = [
  {
    id: "1",
    title: "The Spinning Top",
    description: "The iconic final shot of Inception, where reality and dreams blur together in perfect ambiguity.",
    imageUrl: "/inception-spinning-top.png",
    category: "Symbolism",
    tags: ["dreams", "reality", "ambiguity", "cliffhanger", "nolan"],
    director: "Christopher Nolan",
    cinematographer: "Wally Pfister",
    film: "Inception",
    year: 2010,
    colorPalette: ["#1a1a1a", "#4a4a4a", "#8b7355", "#d4af37", "#f5f5dc"],
    likes: 2847,
    views: 45632,
    aspectRatio: "2.39:1",
    resolution: "4K",
  },
  {
    id: "2",
    title: "Blade Runner 2049 Neon",
    description: "The stunning neon-soaked cityscape that defines the visual language of the future.",
    imageUrl: "/blade-runner-2049-poster.png",
    category: "Lighting",
    tags: ["neon", "cyberpunk", "future", "atmosphere", "deakins"],
    director: "Denis Villeneuve",
    cinematographer: "Roger Deakins",
    film: "Blade Runner 2049",
    year: 2017,
    colorPalette: ["#ff6b35", "#f7931e", "#ffdc00", "#00a8cc", "#005f73"],
    likes: 3421,
    views: 67891,
    aspectRatio: "2.39:1",
    resolution: "4K",
  },
  {
    id: "3",
    title: "Grand Budapest Symmetry",
    description: "Wes Anderson's perfectly symmetrical composition showcasing his distinctive visual style.",
    imageUrl: "/grand-budapest-hotel-poster.png",
    category: "Composition",
    tags: ["symmetry", "pastel", "whimsical", "centered", "anderson"],
    director: "Wes Anderson",
    cinematographer: "Robert Yeoman",
    film: "The Grand Budapest Hotel",
    year: 2014,
    colorPalette: ["#f4c2c2", "#ff6b6b", "#4ecdc4", "#45b7d1", "#96ceb4"],
    likes: 1923,
    views: 34567,
    aspectRatio: "1.85:1",
    resolution: "HD",
  },
  {
    id: "4",
    title: "Mad Max Fury Road Chase",
    description: "High-octane action cinematography with practical effects and dynamic camera movement.",
    imageUrl: "/mad-max-fury-road-poster.png",
    category: "Action",
    tags: ["action", "desert", "practical effects", "movement", "post-apocalyptic"],
    director: "George Miller",
    cinematographer: "John Seale",
    film: "Mad Max: Fury Road",
    year: 2015,
    colorPalette: ["#ff4500", "#ffa500", "#ffff00", "#8b4513", "#2f4f4f"],
    likes: 2156,
    views: 52341,
    aspectRatio: "2.39:1",
    resolution: "4K",
  },
  {
    id: "5",
    title: "Moonlight Blue Hour",
    description: "The ethereal blue lighting that captures the emotional depth of the character's journey.",
    imageUrl: "/moonlight-poster.png",
    category: "Color",
    tags: ["blue hour", "emotion", "intimate", "coming of age", "lgbtq"],
    director: "Barry Jenkins",
    cinematographer: "James Laxton",
    film: "Moonlight",
    year: 2016,
    colorPalette: ["#191970", "#4169e1", "#87ceeb", "#b0e0e6", "#f0f8ff"],
    likes: 1687,
    views: 28934,
    aspectRatio: "1.85:1",
    resolution: "HD",
  },
  {
    id: "6",
    title: "Parasite Stairs",
    description: "The symbolic use of stairs and levels to represent social hierarchy and class division.",
    imageUrl: "/parasite-movie-poster.png",
    category: "Symbolism",
    tags: ["stairs", "class", "symbolism", "architecture", "social commentary"],
    director: "Bong Joon-ho",
    cinematographer: "Hong Kyung-pyo",
    film: "Parasite",
    year: 2019,
    colorPalette: ["#2c2c2c", "#4a4a4a", "#8b8b8b", "#d3d3d3", "#f5f5f5"],
    likes: 3892,
    views: 78234,
    aspectRatio: "2.39:1",
    resolution: "4K",
  },
  {
    id: "7",
    title: "Arrival's First Encounter",
    description: "The awe-inspiring and mysterious arrival of the heptapod ships.",
    imageUrl: "/arrival-poster.png",
    category: "Sci-Fi",
    tags: ["aliens", "mystery", "linguistics", "first contact", "villeneuve"],
    director: "Denis Villeneuve",
    cinematographer: "Bradford Young",
    film: "Arrival",
    year: 2016,
    colorPalette: ["#343a40", "#495057", "#6c757d", "#adb5bd", "#dee2e6"],
    likes: 2950,
    views: 58320,
    aspectRatio: "2.39:1",
    resolution: "4K",
  },
  {
    id: "8",
    title: "Spirited Away Bathhouse",
    description: "The vibrant and fantastical world of the bathhouse in Spirited Away.",
    imageUrl: "/studio-ghibli-poster.png", // Placeholder, ideally specific
    category: "Animation",
    tags: ["ghibli", "fantasy", "spirits", "miyazaki", "world-building"],
    director: "Hayao Miyazaki",
    cinematographer: "Atsushi Okui",
    film: "Spirited Away",
    year: 2001,
    colorPalette: ["#d7263d", "#f46036", "#2e294e", "#1b998b", "#c5d86d"],
    likes: 3105,
    views: 61234,
    aspectRatio: "1.85:1",
    resolution: "HD",
  },
  {
    id: "9",
    title: "The Dark Knight Interrogation",
    description: "The tense and iconic interrogation scene between Batman and Joker.",
    imageUrl: "/dark-knight-poster.png", // Placeholder
    category: "Drama",
    tags: ["interrogation", "tension", "iconic", "nolan", "superhero"],
    director: "Christopher Nolan",
    cinematographer: "Wally Pfister",
    film: "The Dark Knight",
    year: 2008,
    colorPalette: ["#001219", "#005f73", "#0a9396", "#94d2bd", "#e9d8a6"],
    likes: 4012,
    views: 85321,
    aspectRatio: "IMAX",
    resolution: "4K",
  },
  {
    id: "10",
    title: "2001: A Space Odyssey Stargate",
    description: "The psychedelic and groundbreaking Stargate sequence.",
    imageUrl: "/2001-stargate.png",
    category: "Visual Effects",
    tags: ["kubrick", "sci-fi", "classic", "psychedelic", "space"],
    director: "Stanley Kubrick",
    cinematographer: "Geoffrey Unsworth",
    film: "2001: A Space Odyssey",
    year: 1968,
    colorPalette: ["#ef476f", "#ffd166", "#06d6a0", "#118ab2", "#073b4c"],
    likes: 3560,
    views: 72098,
    aspectRatio: "2.20:1",
    resolution: "Restored 4K",
  },
  // Add more diverse entries
  {
    id: "11",
    title: "Hero - Red Battle",
    description: "The visually stunning color-coded fight sequence in 'Hero'.",
    imageUrl: "/heroic-red-battle.png",
    category: "Color",
    tags: ["wuxia", "color theory", "action", "zhang yimou", "martial arts"],
    director: "Zhang Yimou",
    cinematographer: "Christopher Doyle",
    film: "Hero",
    year: 2002,
    colorPalette: ["#dc2f02", "#e85d04", "#f48c06", "#faa307", "#ffba08"],
    likes: 2780,
    views: 55000,
    aspectRatio: "2.35:1",
    resolution: "HD",
  },
  {
    id: "12",
    title: "Children of Men - Car Chase",
    description: "The breathtaking long-take car ambush scene.",
    imageUrl: "/dystopian-car-chase.png",
    category: "Cinematography",
    tags: ["long take", "dystopian", "action", "cuaron", "lubezki"],
    director: "Alfonso Cuarón",
    cinematographer: "Emmanuel Lubezki",
    film: "Children of Men",
    year: 2006,
    colorPalette: ["#52796f", "#84a98c", "#cad2c5", "#354f52", "#2f3e46"],
    likes: 3300,
    views: 69000,
    aspectRatio: "1.85:1",
    resolution: "HD",
  },
  {
    id: "13",
    title: "The Tree of Life - Creation",
    description: "Terrence Malick's poetic and grand depiction of creation.",
    imageUrl: "/placeholder.svg?width=400&height=600",
    category: "Visual Poetry",
    tags: ["malick", "nature", "creation", "philosophical", "lubezki"],
    director: "Terrence Malick",
    cinematographer: "Emmanuel Lubezki",
    film: "The Tree of Life",
    year: 2011,
    colorPalette: ["#0077b6", "#00b4d8", "#90e0ef", "#caf0f8", "#ade8f4"],
    likes: 2400,
    views: 48000,
    aspectRatio: "1.85:1",
    resolution: "HD",
  },
  {
    id: "14",
    title: "Enter the Void - Opening Credits",
    description: "Gaspar Noé's seizure-inducing, typographic opening sequence.",
    imageUrl: "/placeholder.svg?width=400&height=600",
    category: "Experimental",
    tags: ["gaspar noe", "typography", "psychedelic", "controversial", "neon"],
    director: "Gaspar Noé",
    cinematographer: "Benoît Debie",
    film: "Enter the Void",
    year: 2009,
    colorPalette: ["#ff006e", "#f85f73", "#00f5d4", "#8338ec", "#3a86ff"],
    likes: 1800,
    views: 40000,
    aspectRatio: "2.35:1",
    resolution: "HD",
  },
  {
    id: "15",
    title: "The Fall - Costume Design",
    description: "Tarsem Singh's visually opulent world and Eiko Ishioka's costumes.",
    imageUrl: "/placeholder.svg?width=400&height=600",
    category: "Art Direction",
    tags: ["tarsem singh", "costume design", "fantasy", "surreal", "opulent"],
    director: "Tarsem Singh",
    cinematographer: "Colin Watkinson",
    film: "The Fall",
    year: 2006,
    colorPalette: ["#ae2012", "#bb3e03", "#ca6702", "#ee9b00", "#e9c46a"],
    likes: 2900,
    views: 53000,
    aspectRatio: "1.85:1",
    resolution: "HD",
  },
]

export const MOCK_AVAILABLE_FILTERS: AvailableFilters = {
  categories: [
    { name: "Symbolism", count: 2 },
    { name: "Lighting", count: 1 },
    { name: "Composition", count: 1 },
    { name: "Action", count: 2 },
    { name: "Color", count: 2 },
    { name: "Sci-Fi", count: 1 },
    { name: "Animation", count: 1 },
    { name: "Drama", count: 1 },
    { name: "Visual Effects", count: 1 },
    { name: "Cinematography", count: 1 },
    { name: "Visual Poetry", count: 1 },
    { name: "Experimental", count: 1 },
    { name: "Art Direction", count: 1 },
  ],
  tags: [
    { name: "dreams", count: 1 },
    { name: "neon", count: 2 },
    { name: "symmetry", count: 1 },
    { name: "action", count: 3 },
    { name: "emotion", count: 1 },
    { name: "nolan", count: 2 },
    { name: "deakins", count: 1 },
    { name: "anderson", count: 1 },
    { name: "post-apocalyptic", count: 1 },
    { name: "lgbtq", count: 1 },
    { name: "social commentary", count: 1 },
    { name: "villeneuve", count: 1 },
    { name: "ghibli", count: 1 },
    { name: "miyazaki", count: 1 },
    { name: "superhero", count: 1 },
    { name: "kubrick", count: 1 },
    { name: "classic", count: 1 },
    { name: "wuxia", count: 1 },
    { name: "long take", count: 1 },
    { name: "lubezki", count: 2 },
    { name: "malick", count: 1 },
    { name: "gaspar noe", count: 1 },
    { name: "tarsem singh", count: 1 },
  ],
  directors: [
    { name: "Christopher Nolan", count: 2 },
    { name: "Denis Villeneuve", count: 2 },
    { name: "Wes Anderson", count: 1 },
    { name: "George Miller", count: 1 },
    { name: "Barry Jenkins", count: 1 },
    { name: "Bong Joon-ho", count: 1 },
    { name: "Hayao Miyazaki", count: 1 },
    { name: "Stanley Kubrick", count: 1 },
    { name: "Zhang Yimou", count: 1 },
    { name: "Alfonso Cuarón", count: 1 },
    { name: "Terrence Malick", count: 1 },
    { name: "Gaspar Noé", count: 1 },
    { name: "Tarsem Singh", count: 1 },
  ],
  cinematographers: [
    { name: "Wally Pfister", count: 2 },
    { name: "Roger Deakins", count: 1 },
    { name: "Robert Yeoman", count: 1 },
    { name: "John Seale", count: 1 },
    { name: "James Laxton", count: 1 },
    { name: "Hong Kyung-pyo", count: 1 },
    { name: "Bradford Young", count: 1 },
    { name: "Atsushi Okui", count: 1 },
    { name: "Geoffrey Unsworth", count: 1 },
    { name: "Christopher Doyle", count: 1 },
    { name: "Emmanuel Lubezki", count: 2 },
    { name: "Benoît Debie", count: 1 },
    { name: "Colin Watkinson", count: 1 },
  ],
  decades: [
    { name: "2020s", count: 0 },
    { name: "2010s", count: 7 },
    { name: "2000s", count: 6 },
    { name: "1990s", count: 0 },
    { name: "1980s", count: 0 },
    { name: "1960s", count: 1 },
  ],
}

// Function to dynamically update counts (basic simulation)
export const getDynamicAvailableFilters = (treats: VisualTreat[], currentFilters: any): AvailableFilters => {
  const available: AvailableFilters = {
    categories: [],
    tags: [],
    directors: [],
    cinematographers: [],
    decades: [],
  }

  const tempTreats = treats.filter((treat) => {
    // Apply all filters EXCEPT the one being counted
    // This is a simplified version. True dynamic counts are more complex.
    let passes = true
    if (currentFilters.tags.length > 0 && !currentFilters.tags.some((tag) => treat.tags.includes(tag))) passes = false
    // ... add similar checks for other filters if needed for more accuracy
    return passes
  })

  // This is a simplified count based on the *currently displayed* treats if no other filters are active for that category
  // For a more accurate dynamic count, you'd filter by *all other* active filters before counting items for a specific filter type.
  // This is complex for pure frontend, so we'll keep it simpler for now.
  // The MOCK_AVAILABLE_FILTERS provides static overall counts.
  // For a truly dynamic experience, this logic would be more involved or backend-driven.

  return MOCK_AVAILABLE_FILTERS // Returning static for now, dynamic is complex
}
