import type { CriticProfile, CriticReview } from "@/types/critic"

export function generateMockCriticProfile(username: string): CriticProfile {
  const profiles: Record<string, CriticProfile> = {
    siddu: {
      id: 1,
      external_id: "critic_siddu_001",
      username: "siddu",
      display_name: "Siddu Kumar",
      bio: "Film critic and cinephile. Passionate about storytelling and visual artistry. 15+ years of experience reviewing films across all genres.",
      avatar_url: "/critic-avatar-1.png",
      banner_image_url: "/critic-banner-1.png",
      banner_video_url: "https://youtube.com/watch?v=example1",
      is_verified: true,
      verification_level: "professional",
      total_reviews: 342,
      total_followers: 125000,
      total_following: 450,
      avg_rating: 7.8,
      total_likes: 45000,
      total_views: 1200000,
      joined_at: "2024-01-15T00:00:00Z",
      social_links: [
        { id: 1, platform: "YouTube", url: "https://youtube.com/@siddukumar", display_text: "@siddukumar" },
        { id: 2, platform: "Twitter", url: "https://twitter.com/siddukumar", display_text: "@siddukumar" },
        { id: 3, platform: "Instagram", url: "https://instagram.com/siddukumar", display_text: "@siddukumar" },
      ],
    },
    arjun_movies: {
      id: 4,
      external_id: "critic_arjun_004",
      username: "arjun_movies",
      display_name: "Arjun Patel",
      bio: "Action and thriller specialist. 5 years of professional film criticism. Regular contributor to major entertainment websites.",
      avatar_url: "/critic-avatar-4.png",
      banner_image_url: "/critic-banner-4.png",
      banner_video_url: null,
      is_verified: true,
      verification_level: "basic",
      total_reviews: 156,
      total_followers: 54000,
      total_following: 320,
      avg_rating: 7.2,
      total_likes: 18000,
      total_views: 450000,
      joined_at: "2024-06-25T00:00:00Z",
      social_links: [
        { id: 10, platform: "Twitter", url: "https://twitter.com/arjunmovies", display_text: "@arjunmovies" },
        { id: 11, platform: "Instagram", url: "https://instagram.com/arjunmovies", display_text: "@arjunmovies" },
      ],
    },
    rajesh_cinema: {
      id: 2,
      external_id: "critic_rajesh_002",
      username: "rajesh_cinema",
      display_name: "Rajesh Menon",
      bio: "Bollywood and international cinema expert. Former film school professor. Specializing in narrative analysis.",
      avatar_url: "/critic-avatar-2.png",
      banner_image_url: "/critic-banner-2.png",
      banner_video_url: null,
      is_verified: true,
      verification_level: "professional",
      total_reviews: 215,
      total_followers: 89000,
      total_following: 380,
      avg_rating: 7.5,
      total_likes: 32000,
      total_views: 780000,
      joined_at: "2024-03-20T00:00:00Z",
      social_links: [
        { id: 4, platform: "YouTube", url: "https://youtube.com/@rajeshcinema", display_text: "@rajeshcinema" },
        { id: 5, platform: "Twitter", url: "https://twitter.com/rajeshcinema", display_text: "@rajeshcinema" },
      ],
    },
    priya_reviews: {
      id: 3,
      external_id: "critic_priya_003",
      username: "priya_reviews",
      display_name: "Priya Sharma",
      bio: "Drama and romance expert. 10 years of experience in film journalism. Award-winning critic.",
      avatar_url: "/critic-avatar-3.png",
      banner_image_url: "/critic-banner-3.png",
      banner_video_url: null,
      is_verified: true,
      verification_level: "professional",
      total_reviews: 178,
      total_followers: 67000,
      total_following: 290,
      avg_rating: 8.1,
      total_likes: 25000,
      total_views: 620000,
      joined_at: "2024-05-10T00:00:00Z",
      social_links: [
        { id: 7, platform: "YouTube", url: "https://youtube.com/@priyareviews", display_text: "@priyareviews" },
        { id: 8, platform: "Twitter", url: "https://twitter.com/priyareviews", display_text: "@priyareviews" },
        { id: 9, platform: "Instagram", url: "https://instagram.com/priyareviews", display_text: "@priyareviews" },
      ],
    },
    neha_film: {
      id: 5,
      external_id: "critic_neha_005",
      username: "neha_film",
      display_name: "Neha Kapoor",
      bio: "Independent film critic focusing on world cinema. Published author and podcast host.",
      avatar_url: "/critic-avatar-5.png",
      banner_image_url: "/critic-banner-5.png",
      banner_video_url: null,
      is_verified: true,
      verification_level: "basic",
      total_reviews: 134,
      total_followers: 42000,
      total_following: 250,
      avg_rating: 7.9,
      total_likes: 15000,
      total_views: 380000,
      joined_at: "2024-08-05T00:00:00Z",
      social_links: [
        { id: 12, platform: "Twitter", url: "https://twitter.com/nehafilm", display_text: "@nehafilm" },
      ],
    },
  }

  return profiles[username] || profiles.siddu
}

export function generateMockCriticReviews(username: string): CriticReview[] {
  const baseReviews: CriticReview[] = [
    {
      id: 1,
      external_id: "review_001",
      title: "The Shawshank Redemption",
      content:
        "The Shawshank Redemption is a masterclass in storytelling. Tim Robbins and Morgan Freeman deliver career-defining performances in this tale of hope, friendship, and redemption. Frank Darabont's direction is impeccable, creating a film that resonates emotionally while maintaining perfect pacing. The cinematography by Roger Deakins captures both the bleakness of prison life and the beauty of hope. Thomas Newman's score is hauntingly beautiful. This is not just a great prison film; it's one of the greatest films ever made.",
      rating: 9.8,
      slug: "shawshank-redemption-masterpiece",
      published_at: "2025-10-15T10:00:00Z",
      likes_count: 3200,
      comments_count: 450,
      views_count: 45000,
      movie: {
        id: 1,
        external_id: "tt0111161",
        title: "The Shawshank Redemption",
        poster_url: "/shawshank-redemption-poster.png",
        year: "1994",
      },
    },
    {
      id: 2,
      external_id: "review_002",
      title: "The Dark Knight",
      content:
        "Christopher Nolan elevates the superhero genre to new heights with The Dark Knight. Heath Ledger's Joker is a tour de force performance that will be remembered for generations. The film explores themes of chaos, morality, and sacrifice with unprecedented depth for a comic book adaptation. The action sequences are breathtaking, the cinematography is stunning, and Hans Zimmer's score is iconic. This is filmmaking at its finest.",
      rating: 9.5,
      slug: "dark-knight-superhero-masterpiece",
      published_at: "2025-10-12T14:30:00Z",
      likes_count: 4100,
      comments_count: 580,
      views_count: 52000,
      movie: {
        id: 2,
        external_id: "tt0468569",
        title: "The Dark Knight",
        poster_url: "/dark-knight-poster.png",
        year: "2008",
      },
    },
    {
      id: 3,
      external_id: "review_003",
      title: "Inception",
      content:
        "Inception is a mind-bending masterpiece that challenges audiences to question reality itself. Christopher Nolan crafts a complex narrative that rewards multiple viewings. The visual effects are groundbreaking, particularly the rotating hallway fight scene. Leonardo DiCaprio anchors the film with an emotional performance. Hans Zimmer's score, especially 'Time,' is unforgettable. This is intelligent blockbuster filmmaking at its best.",
      rating: 9.3,
      slug: "inception-mind-bending-masterpiece",
      published_at: "2025-10-08T16:00:00Z",
      likes_count: 2900,
      comments_count: 420,
      views_count: 38000,
      movie: {
        id: 3,
        external_id: "tt1375666",
        title: "Inception",
        poster_url: "/inception-movie-poster.png",
        year: "2010",
      },
    },
  ]

  return baseReviews
}

